/**
 * lib/briefs/static-registry.ts — BUILD-TIME BRIEF REGISTRY
 *
 * Loads brief metadata from public/system/briefs-registry.json using a
 * lazy require(). The JSON is generated by scripts/generate-briefs-registry.mjs
 * (runs after contentlayer2 build, before next build).
 *
 * Because require() with a JSON file is resolved at module load time and
 * bundled by Next.js webpack, the data is embedded in the JS chunk at build
 * time. Zero filesystem reads at runtime on Netlify serverless.
 */

export type BriefMeta = {
  slug: string;
  flattenedPath: string;
  title: string;
  subtitle?: string;
  description?: string;
  excerpt?: string;
  date?: string;
  lastUpdated?: string;
  category?: string;
  tags?: string[];
  status?: string;
  institutionalId?: string;
  version?: string;
  classification?: string;
  accessTierSafe: string;
  publishedSafe: boolean;
  requiresAuthSafe: boolean;
};

let _registry: BriefMeta[] | null = null;

function loadRegistry(): BriefMeta[] {
  if (_registry) return _registry;

  try {
    // Try direct require first — works when webpack bundles it
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    _registry = require("../../public/system/briefs-registry.json") as BriefMeta[];
    return _registry;
  } catch {
    try {
      // Fallback: absolute path for runtime (Netlify serverless)
      const fs = require("fs") as typeof import("fs");
      const path = require("path") as typeof import("path");
      const p = path.join(process.cwd(), "public", "system", "briefs-registry.json");
      if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, "utf-8");
        _registry = JSON.parse(raw) as BriefMeta[];
        return _registry;
      }
    } catch {
      // ignore
    }
  }

  console.warn("[BRIEFS_REGISTRY] briefs-registry.json not found. Run: pnpm build:netlify");
  _registry = [];
  return _registry;
}

/**
 * Get all briefs from the static registry.
 * Data is bundled at build time — no runtime filesystem access needed.
 */
export function getAllBriefsFromRegistry(): BriefMeta[] {
  return loadRegistry();
}

/**
 * Find a brief by its URL slug.
 */
export function findBriefBySlug(slug: string): BriefMeta | undefined {
  const s = String(slug || "").trim();
  if (!s) return undefined;

  return loadRegistry().find((b) => {
    const fp = b.flattenedPath;
    return fp === `briefs/${s}` || fp === `vault/briefs/${s}`;
  });
}