/**
 * lib/briefs/static-registry.ts — BRIEF REGISTRY (RUNTIME-SAFE)
 *
 * Loads brief metadata from public/system/briefs-registry.json, which is
 * generated by scripts/generate-briefs-registry.mjs (runs after contentlayer2
 * build, before next build).
 *
 * Uses require() to load the JSON. On Netlify serverless, the file is in
 * public/ which is deployed as a static asset and accessible from the
 * serverless function's filesystem at process.cwd().
 *
 * Falls back gracefully to empty array if the file is missing.
 */

import fs from "fs";
import path from "path";

export type BriefMeta = {
  slug: string;
  flattenedPath: string;
  title: string;
  subtitle?: string;
  description?: string;
  excerpt?: string;
  date?: string;
  lastUpdated?: string;
  category?: string;
  tags?: string[];
  status?: string;
  institutionalId?: string;
  version?: string;
  classification?: string;
  accessTierSafe: string;
  publishedSafe: boolean;
  requiresAuthSafe: boolean;
};

let _registry: BriefMeta[] | null = null;

function loadRegistry(): BriefMeta[] {
  if (_registry) return _registry;

  // Try multiple paths — build-time (process.cwd() = project root),
  // Netlify serverless runtime, and relative fallback.
  const candidates = [
    path.join(process.cwd(), "public", "system", "briefs-registry.json"),
    path.join(process.cwd(), "system", "briefs-registry.json"),
    path.resolve(__dirname, "..", "..", "public", "system", "briefs-registry.json"),
    path.resolve(__dirname, "..", "..", "..", "public", "system", "briefs-registry.json"),
  ];

  for (const candidate of candidates) {
    try {
      if (fs.existsSync(candidate)) {
        const raw = fs.readFileSync(candidate, "utf-8");
        _registry = JSON.parse(raw) as BriefMeta[];
        return _registry;
      }
    } catch {
      // try next candidate
    }
  }

  // Last resort: try require() which works when webpack bundles it
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    _registry = require("../../public/system/briefs-registry.json") as BriefMeta[];
    return _registry;
  } catch {
    // ignore
  }

  console.warn("[BRIEFS_REGISTRY] briefs-registry.json not found. Run: pnpm build:netlify");
  _registry = [];
  return _registry;
}

/**
 * Get all briefs from the static registry.
 */
export function getAllBriefsFromRegistry(): BriefMeta[] {
  return loadRegistry();
}

/**
 * Find a brief by its URL slug.
 */
export function findBriefBySlug(slug: string): BriefMeta | undefined {
  const s = String(slug || "").trim();
  if (!s) return undefined;

  return loadRegistry().find((b) => {
    const fp = b.flattenedPath;
    return fp === `briefs/${s}` || fp === `vault/briefs/${s}`;
  });
}
