// lib/pdf/pdf-registry.generated.ts
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Generated: 2026-05-20T18:43:45.452Z

import type { PDFRegistryEntry } from "./registry.static";

export const GENERATED_PDF_CONFIGS: ReadonlyArray<PDFRegistryEntry> = [
  {
    "id": "audit-of-ease",
    "title": "Audit Of Ease",
    "description": "Audit Of Ease — Abraham of London resource.",
    "excerpt": "Audit Of Ease.",
    "outputPath": "/assets/downloads/audit-of-ease.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "audit-of-easepdf",
    "categorySlug": "audit-of-easepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 81398,
    "fileSizeHuman": "79.5 KB",
    "lastModified": "2026-05-09T02:06:19.686Z",
    "md5": "d35c3d8b77cc8b4ee63538c716e9f5ed",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "canon-builders-rule-of-life",
    "title": "Canon Builders Rule Of Life",
    "description": "Canon Builders Rule Of Life — Abraham of London resource.",
    "excerpt": "Canon Builders Rule Of Life.",
    "outputPath": "/assets/downloads/canon-builders-rule-of-life.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "canon-builders-rule-of-lifepdf",
    "categorySlug": "canon-builders-rule-of-lifepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 46422,
    "fileSizeHuman": "45.3 KB",
    "lastModified": "2026-05-09T02:06:19.693Z",
    "md5": "841331546bfb42080a0d0ecc3ff516a9",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_45KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "canon-system-constitution",
    "title": "Canon System Constitution",
    "description": "Canon System Constitution — Abraham of London resource.",
    "excerpt": "Canon System Constitution.",
    "outputPath": "/assets/downloads/canon-system-constitution.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "canon-system-constitutionpdf",
    "categorySlug": "canon-system-constitutionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 95692,
    "fileSizeHuman": "93.4 KB",
    "lastModified": "2026-05-09T02:06:19.691Z",
    "md5": "6dc102a41d04b3bcf7bf7a109e066381",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-01",
    "title": "Frontier Resilience 01",
    "description": "Frontier Resilience 01 — Abraham of London resource.",
    "excerpt": "Frontier Resilience 01.",
    "outputPath": "/assets/downloads/content-downloads/frontier-resilience-01.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "content-downloads",
    "categorySlug": "content-downloads",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 77084,
    "fileSizeHuman": "75.3 KB",
    "lastModified": "2026-05-09T02:06:22.299Z",
    "md5": "d2d1c06919ddc63f04edbbe2cfe2185f",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "conviction-vs-coercion",
    "title": "Conviction Vs Coercion",
    "description": "Conviction Vs Coercion — Abraham of London resource.",
    "excerpt": "Conviction Vs Coercion.",
    "outputPath": "/assets/downloads/conviction-vs-coercion.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "conviction-vs-coercionpdf",
    "categorySlug": "conviction-vs-coercionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 82921,
    "fileSizeHuman": "81.0 KB",
    "lastModified": "2026-05-09T02:06:19.706Z",
    "md5": "8bab253d00dcc9cae2f217fb2ef3bbcf",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "extremism-shield",
    "title": "Extremism Shield",
    "description": "Extremism Shield — Abraham of London resource.",
    "excerpt": "Extremism Shield.",
    "outputPath": "/assets/downloads/extremism-shield.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "extremism-shieldpdf",
    "categorySlug": "extremism-shieldpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48104,
    "fileSizeHuman": "47.0 KB",
    "lastModified": "2026-05-09T02:06:56.837Z",
    "md5": "828256e1afa4d91cf74138c41f6d9954",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-beyond-survival-mode",
    "title": "Frontier Resilience Beyond Survival Mode",
    "description": "Frontier Resilience Beyond Survival Mode — Abraham of London resource.",
    "excerpt": "Frontier Resilience Beyond Survival Mode.",
    "outputPath": "/assets/downloads/frontier-resilience-beyond-survival-mode.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-beyond-survival-modepdf",
    "categorySlug": "frontier-resilience-beyond-survival-modepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48776,
    "fileSizeHuman": "47.6 KB",
    "lastModified": "2026-05-09T02:06:22.299Z",
    "md5": "1072f7c2d86ebfb201413f49f5a1e1c3",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-crisis-loops-and-lost-judgment",
    "title": "Frontier Resilience Crisis Loops And Lost Judgment",
    "description": "Frontier Resilience Crisis Loops And Lost Judgment — Abraham of London resource.",
    "excerpt": "Frontier Resilience Crisis Loops And Lost Judgment.",
    "outputPath": "/assets/downloads/frontier-resilience-crisis-loops-and-lost-judgment.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-crisis-loops-and-lost-judgmentpdf",
    "categorySlug": "frontier-resilience-crisis-loops-and-lost-judgmentpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49394,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:22.322Z",
    "md5": "a9990074f521c7fdceb887b68a74abbb",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-decision-latency-as-hidden-risk",
    "title": "Frontier Resilience Decision Latency As Hidden Risk",
    "description": "Frontier Resilience Decision Latency As Hidden Risk — Abraham of London resource.",
    "excerpt": "Frontier Resilience Decision Latency As Hidden Risk.",
    "outputPath": "/assets/downloads/frontier-resilience-decision-latency-as-hidden-risk.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-decision-latency-as-hidden-riskpdf",
    "categorySlug": "frontier-resilience-decision-latency-as-hidden-riskpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49479,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:22.315Z",
    "md5": "6a6c340839a6eea6c92dc17bcf22043a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-drift-in-the-second-line",
    "title": "Frontier Resilience Drift In The Second Line",
    "description": "Frontier Resilience Drift In The Second Line — Abraham of London resource.",
    "excerpt": "Frontier Resilience Drift In The Second Line.",
    "outputPath": "/assets/downloads/frontier-resilience-drift-in-the-second-line.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-drift-in-the-second-linepdf",
    "categorySlug": "frontier-resilience-drift-in-the-second-linepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48370,
    "fileSizeHuman": "47.2 KB",
    "lastModified": "2026-05-09T02:06:23.889Z",
    "md5": "0496f8dec46ce3c36c4d44127f3e4bc0",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-drift-inside-the-winning-season",
    "title": "Frontier Resilience Drift Inside The Winning Season",
    "description": "Frontier Resilience Drift Inside The Winning Season — Abraham of London resource.",
    "excerpt": "Frontier Resilience Drift Inside The Winning Season.",
    "outputPath": "/assets/downloads/frontier-resilience-drift-inside-the-winning-season.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-drift-inside-the-winning-seasonpdf",
    "categorySlug": "frontier-resilience-drift-inside-the-winning-seasonpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49132,
    "fileSizeHuman": "48.0 KB",
    "lastModified": "2026-05-09T02:06:23.891Z",
    "md5": "a460f5679257281bc58f3492d4f00d6e",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-fatigue-at-the-top",
    "title": "Frontier Resilience Fatigue At The Top",
    "description": "Frontier Resilience Fatigue At The Top — Abraham of London resource.",
    "excerpt": "Frontier Resilience Fatigue At The Top.",
    "outputPath": "/assets/downloads/frontier-resilience-fatigue-at-the-top.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-fatigue-at-the-toppdf",
    "categorySlug": "frontier-resilience-fatigue-at-the-toppdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48920,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:23.894Z",
    "md5": "135da4dc9f88035bb576811c2f0fad82",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-founder-endurance-is-not-a-plan",
    "title": "Frontier Resilience Founder Endurance Is Not A Plan",
    "description": "Frontier Resilience Founder Endurance Is Not A Plan — Abraham of London resource.",
    "excerpt": "Frontier Resilience Founder Endurance Is Not A Plan.",
    "outputPath": "/assets/downloads/frontier-resilience-founder-endurance-is-not-a-plan.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-founder-endurance-is-not-a-planpdf",
    "categorySlug": "frontier-resilience-founder-endurance-is-not-a-planpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49008,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:23.878Z",
    "md5": "e0682090964c7a0fbf8d38443bccaf98",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-fragility-of-unowned-decisions",
    "title": "Frontier Resilience Fragility Of Unowned Decisions",
    "description": "Frontier Resilience Fragility Of Unowned Decisions — Abraham of London resource.",
    "excerpt": "Frontier Resilience Fragility Of Unowned Decisions.",
    "outputPath": "/assets/downloads/frontier-resilience-fragility-of-unowned-decisions.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-fragility-of-unowned-decisionspdf",
    "categorySlug": "frontier-resilience-fragility-of-unowned-decisionspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50253,
    "fileSizeHuman": "49.1 KB",
    "lastModified": "2026-05-09T02:06:25.548Z",
    "md5": "7557f2665b01cb59a9c8858b7cce66f2",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-holding-standard-when-cash-tightens",
    "title": "Frontier Resilience Holding Standard When Cash Tightens",
    "description": "Frontier Resilience Holding Standard When Cash Tightens — Abraham of London resource.",
    "excerpt": "Frontier Resilience Holding Standard When Cash Tightens.",
    "outputPath": "/assets/downloads/frontier-resilience-holding-standard-when-cash-tightens.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-holding-standard-when-cash-tightenspdf",
    "categorySlug": "frontier-resilience-holding-standard-when-cash-tightenspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49380,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:25.552Z",
    "md5": "34b3ad4ea25e64f5817ccd0bf513fc53",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-institutions-that-cannot-say-no",
    "title": "Frontier Resilience Institutions That Cannot Say No",
    "description": "Frontier Resilience Institutions That Cannot Say No — Abraham of London resource.",
    "excerpt": "Frontier Resilience Institutions That Cannot Say No.",
    "outputPath": "/assets/downloads/frontier-resilience-institutions-that-cannot-say-no.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-institutions-that-cannot-say-nopdf",
    "categorySlug": "frontier-resilience-institutions-that-cannot-say-nopdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48414,
    "fileSizeHuman": "47.3 KB",
    "lastModified": "2026-05-09T02:06:25.556Z",
    "md5": "089ada9a96aa14b2bc09a6d76672ee2f",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-operating-cadence-under-strain",
    "title": "Frontier Resilience Operating Cadence Under Strain",
    "description": "Frontier Resilience Operating Cadence Under Strain — Abraham of London resource.",
    "excerpt": "Frontier Resilience Operating Cadence Under Strain.",
    "outputPath": "/assets/downloads/frontier-resilience-operating-cadence-under-strain.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-operating-cadence-under-strainpdf",
    "categorySlug": "frontier-resilience-operating-cadence-under-strainpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48853,
    "fileSizeHuman": "47.7 KB",
    "lastModified": "2026-05-09T02:06:25.548Z",
    "md5": "a3118ea7c5fdf623232107a7d693f94a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-pressure-tests-for-key-person-risk",
    "title": "Frontier Resilience Pressure Tests For Key Person Risk",
    "description": "Frontier Resilience Pressure Tests For Key Person Risk — Abraham of London resource.",
    "excerpt": "Frontier Resilience Pressure Tests For Key Person Risk.",
    "outputPath": "/assets/downloads/frontier-resilience-pressure-tests-for-key-person-risk.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-pressure-tests-for-key-person-riskpdf",
    "categorySlug": "frontier-resilience-pressure-tests-for-key-person-riskpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49537,
    "fileSizeHuman": "48.4 KB",
    "lastModified": "2026-05-09T02:06:27.164Z",
    "md5": "1459a8432cf5439b2d35906d537ebcf9",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-resilience-before-expansion",
    "title": "Frontier Resilience Resilience Before Expansion",
    "description": "Frontier Resilience Resilience Before Expansion — Abraham of London resource.",
    "excerpt": "Frontier Resilience Resilience Before Expansion.",
    "outputPath": "/assets/downloads/frontier-resilience-resilience-before-expansion.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-resilience-before-expansionpdf",
    "categorySlug": "frontier-resilience-resilience-before-expansionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48062,
    "fileSizeHuman": "46.9 KB",
    "lastModified": "2026-05-09T02:06:27.169Z",
    "md5": "fe972a5f1cea14d763e2ea89b8d2d16a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-restoring-command-after-confusion",
    "title": "Frontier Resilience Restoring Command After Confusion",
    "description": "Frontier Resilience Restoring Command After Confusion — Abraham of London resource.",
    "excerpt": "Frontier Resilience Restoring Command After Confusion.",
    "outputPath": "/assets/downloads/frontier-resilience-restoring-command-after-confusion.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-restoring-command-after-confusionpdf",
    "categorySlug": "frontier-resilience-restoring-command-after-confusionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49145,
    "fileSizeHuman": "48.0 KB",
    "lastModified": "2026-05-09T02:06:27.154Z",
    "md5": "a7464b5299c05b7a839bab1bb750ced6",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-stress-reveals-the-real-culture",
    "title": "Frontier Resilience Stress Reveals The Real Culture",
    "description": "Frontier Resilience Stress Reveals The Real Culture — Abraham of London resource.",
    "excerpt": "Frontier Resilience Stress Reveals The Real Culture.",
    "outputPath": "/assets/downloads/frontier-resilience-stress-reveals-the-real-culture.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-stress-reveals-the-real-culturepdf",
    "categorySlug": "frontier-resilience-stress-reveals-the-real-culturepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48516,
    "fileSizeHuman": "47.4 KB",
    "lastModified": "2026-05-09T02:06:27.158Z",
    "md5": "1a8cc6b6874ae04725b1a49a145756f6",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-surviving-bad-information",
    "title": "Frontier Resilience Surviving Bad Information",
    "description": "Frontier Resilience Surviving Bad Information — Abraham of London resource.",
    "excerpt": "Frontier Resilience Surviving Bad Information.",
    "outputPath": "/assets/downloads/frontier-resilience-surviving-bad-information.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-surviving-bad-informationpdf",
    "categorySlug": "frontier-resilience-surviving-bad-informationpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48854,
    "fileSizeHuman": "47.7 KB",
    "lastModified": "2026-05-09T02:06:28.875Z",
    "md5": "2a3ec6d4d988b0f2a1d2767c5812ea25",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-the-cost-of-living-in-escalation",
    "title": "Frontier Resilience The Cost Of Living In Escalation",
    "description": "Frontier Resilience The Cost Of Living In Escalation — Abraham of London resource.",
    "excerpt": "Frontier Resilience The Cost Of Living In Escalation.",
    "outputPath": "/assets/downloads/frontier-resilience-the-cost-of-living-in-escalation.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-the-cost-of-living-in-escalationpdf",
    "categorySlug": "frontier-resilience-the-cost-of-living-in-escalationpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48410,
    "fileSizeHuman": "47.3 KB",
    "lastModified": "2026-05-09T02:06:28.889Z",
    "md5": "954cdf3082bd89eaced2b6412d8cabed",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_47KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-the-discipline-of-bounded-adaptation",
    "title": "Frontier Resilience The Discipline Of Bounded Adaptation",
    "description": "Frontier Resilience The Discipline Of Bounded Adaptation — Abraham of London resource.",
    "excerpt": "Frontier Resilience The Discipline Of Bounded Adaptation.",
    "outputPath": "/assets/downloads/frontier-resilience-the-discipline-of-bounded-adaptation.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-the-discipline-of-bounded-adaptationpdf",
    "categorySlug": "frontier-resilience-the-discipline-of-bounded-adaptationpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49398,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:28.875Z",
    "md5": "63d908e1538aa89ad185f0e8b49168cf",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-the-false-order-of-busy-teams",
    "title": "Frontier Resilience The False Order Of Busy Teams",
    "description": "Frontier Resilience The False Order Of Busy Teams — Abraham of London resource.",
    "excerpt": "Frontier Resilience The False Order Of Busy Teams.",
    "outputPath": "/assets/downloads/frontier-resilience-the-false-order-of-busy-teams.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-the-false-order-of-busy-teamspdf",
    "categorySlug": "frontier-resilience-the-false-order-of-busy-teamspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49161,
    "fileSizeHuman": "48.0 KB",
    "lastModified": "2026-05-09T02:06:28.887Z",
    "md5": "5dd605ae7b5194332a000beb4490c87a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-the-fragility-of-heroic-leadership",
    "title": "Frontier Resilience The Fragility Of Heroic Leadership",
    "description": "Frontier Resilience The Fragility Of Heroic Leadership — Abraham of London resource.",
    "excerpt": "Frontier Resilience The Fragility Of Heroic Leadership.",
    "outputPath": "/assets/downloads/frontier-resilience-the-fragility-of-heroic-leadership.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-the-fragility-of-heroic-leadershippdf",
    "categorySlug": "frontier-resilience-the-fragility-of-heroic-leadershippdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49242,
    "fileSizeHuman": "48.1 KB",
    "lastModified": "2026-05-09T02:06:30.816Z",
    "md5": "4900f7870bf810bc771f8da8b2ff02c7",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-the-tax-of-constant-reaction",
    "title": "Frontier Resilience The Tax Of Constant Reaction",
    "description": "Frontier Resilience The Tax Of Constant Reaction — Abraham of London resource.",
    "excerpt": "Frontier Resilience The Tax Of Constant Reaction.",
    "outputPath": "/assets/downloads/frontier-resilience-the-tax-of-constant-reaction.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-the-tax-of-constant-reactionpdf",
    "categorySlug": "frontier-resilience-the-tax-of-constant-reactionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49143,
    "fileSizeHuman": "48.0 KB",
    "lastModified": "2026-05-09T02:06:30.820Z",
    "md5": "04097666f0ae53c059696193ac66dd2c",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-when-clarity-has-no-owner",
    "title": "Frontier Resilience When Clarity Has No Owner",
    "description": "Frontier Resilience When Clarity Has No Owner — Abraham of London resource.",
    "excerpt": "Frontier Resilience When Clarity Has No Owner.",
    "outputPath": "/assets/downloads/frontier-resilience-when-clarity-has-no-owner.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-when-clarity-has-no-ownerpdf",
    "categorySlug": "frontier-resilience-when-clarity-has-no-ownerpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49057,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:30.806Z",
    "md5": "081063d6f7681144e009af6373d01525",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-when-growth-hides-breakdown",
    "title": "Frontier Resilience When Growth Hides Breakdown",
    "description": "Frontier Resilience When Growth Hides Breakdown — Abraham of London resource.",
    "excerpt": "Frontier Resilience When Growth Hides Breakdown.",
    "outputPath": "/assets/downloads/frontier-resilience-when-growth-hides-breakdown.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-when-growth-hides-breakdownpdf",
    "categorySlug": "frontier-resilience-when-growth-hides-breakdownpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50112,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:30.814Z",
    "md5": "7842e3c1552d11b6a6310b5bb12945fe",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-when-recovery-needs-governance",
    "title": "Frontier Resilience When Recovery Needs Governance",
    "description": "Frontier Resilience When Recovery Needs Governance — Abraham of London resource.",
    "excerpt": "Frontier Resilience When Recovery Needs Governance.",
    "outputPath": "/assets/downloads/frontier-resilience-when-recovery-needs-governance.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-when-recovery-needs-governancepdf",
    "categorySlug": "frontier-resilience-when-recovery-needs-governancepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49305,
    "fileSizeHuman": "48.1 KB",
    "lastModified": "2026-05-09T02:06:33.340Z",
    "md5": "a7dcd26e670cd6d39f235ac2431d20ae",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "frontier-resilience-when-urgency-corrupts-sequencing",
    "title": "Frontier Resilience When Urgency Corrupts Sequencing",
    "description": "Frontier Resilience When Urgency Corrupts Sequencing — Abraham of London resource.",
    "excerpt": "Frontier Resilience When Urgency Corrupts Sequencing.",
    "outputPath": "/assets/downloads/frontier-resilience-when-urgency-corrupts-sequencing.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "frontier-resilience-when-urgency-corrupts-sequencingpdf",
    "categorySlug": "frontier-resilience-when-urgency-corrupts-sequencingpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49383,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:33.340Z",
    "md5": "7cce29140c8e499ca345e33365aaaeec",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "governance-diagnostic-toolkit",
    "title": "Governance Diagnostic Toolkit",
    "description": "Governance Diagnostic Toolkit — Abraham of London resource.",
    "excerpt": "Governance Diagnostic Toolkit.",
    "outputPath": "/assets/downloads/governance-diagnostic-toolkit.pdf",
    "type": "assessment",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "governance-diagnostic-toolkitpdf",
    "categorySlug": "governance-diagnostic-toolkitpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 82227,
    "fileSizeHuman": "80.3 KB",
    "lastModified": "2026-05-09T02:06:33.353Z",
    "md5": "118db9e113f1cff1b03956fd2e41080b",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-false-confidence-from-aggregated-metrics",
    "title": "Institutional Alpha False Confidence From Aggregated Metrics",
    "description": "Institutional Alpha False Confidence From Aggregated Metrics — Abraham of London resource.",
    "excerpt": "Institutional Alpha False Confidence From Aggregated Metrics.",
    "outputPath": "/assets/downloads/institutional-alpha-false-confidence-from-aggregated-metrics.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-false-confidence-from-aggregated-metricspdf",
    "categorySlug": "institutional-alpha-false-confidence-from-aggregated-metricspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49638,
    "fileSizeHuman": "48.5 KB",
    "lastModified": "2026-05-09T02:06:33.361Z",
    "md5": "288acfdca4955bcfbbb5598a5ad10b3a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-intelligence-after-the-founder-myth",
    "title": "Institutional Alpha Intelligence After The Founder Myth",
    "description": "Institutional Alpha Intelligence After The Founder Myth — Abraham of London resource.",
    "excerpt": "Institutional Alpha Intelligence After The Founder Myth.",
    "outputPath": "/assets/downloads/institutional-alpha-intelligence-after-the-founder-myth.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-intelligence-after-the-founder-mythpdf",
    "categorySlug": "institutional-alpha-intelligence-after-the-founder-mythpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49460,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:35.302Z",
    "md5": "1df2eec8e94a97df1f7d01cf214bd0bf",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-intelligence-debt-in-scaling-firms",
    "title": "Institutional Alpha Intelligence Debt In Scaling Firms",
    "description": "Institutional Alpha Intelligence Debt In Scaling Firms — Abraham of London resource.",
    "excerpt": "Institutional Alpha Intelligence Debt In Scaling Firms.",
    "outputPath": "/assets/downloads/institutional-alpha-intelligence-debt-in-scaling-firms.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-intelligence-debt-in-scaling-firmspdf",
    "categorySlug": "institutional-alpha-intelligence-debt-in-scaling-firmspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49250,
    "fileSizeHuman": "48.1 KB",
    "lastModified": "2026-05-09T02:06:35.308Z",
    "md5": "73520b407a5cee3911b0ea267a9bea84",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-intelligence-drift-after-rapid-expansion",
    "title": "Institutional Alpha Intelligence Drift After Rapid Expansion",
    "description": "Institutional Alpha Intelligence Drift After Rapid Expansion — Abraham of London resource.",
    "excerpt": "Institutional Alpha Intelligence Drift After Rapid Expansion.",
    "outputPath": "/assets/downloads/institutional-alpha-intelligence-drift-after-rapid-expansion.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-intelligence-drift-after-rapid-expansionpdf",
    "categorySlug": "institutional-alpha-intelligence-drift-after-rapid-expansionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49675,
    "fileSizeHuman": "48.5 KB",
    "lastModified": "2026-05-09T02:06:35.304Z",
    "md5": "7e91034f744da20b009c0c87b96790ec",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-overinterpreting-motion-as-momentum",
    "title": "Institutional Alpha Overinterpreting Motion As Momentum",
    "description": "Institutional Alpha Overinterpreting Motion As Momentum — Abraham of London resource.",
    "excerpt": "Institutional Alpha Overinterpreting Motion As Momentum.",
    "outputPath": "/assets/downloads/institutional-alpha-overinterpreting-motion-as-momentum.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-overinterpreting-motion-as-momentumpdf",
    "categorySlug": "institutional-alpha-overinterpreting-motion-as-momentumpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48964,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:35.296Z",
    "md5": "d4b9ccf44b25dc0e1fe0dc86d2708352",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-pattern-recognition-without-operating-truth",
    "title": "Institutional Alpha Pattern Recognition Without Operating Truth",
    "description": "Institutional Alpha Pattern Recognition Without Operating Truth — Abraham of London resource.",
    "excerpt": "Institutional Alpha Pattern Recognition Without Operating Truth.",
    "outputPath": "/assets/downloads/institutional-alpha-pattern-recognition-without-operating-truth.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-pattern-recognition-without-operating-truthpdf",
    "categorySlug": "institutional-alpha-pattern-recognition-without-operating-truthpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50081,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:37.196Z",
    "md5": "3cae0dcafefcbcef21578ee15bad33ba",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-reporting-systems-that-reward-optimism",
    "title": "Institutional Alpha Reporting Systems That Reward Optimism",
    "description": "Institutional Alpha Reporting Systems That Reward Optimism — Abraham of London resource.",
    "excerpt": "Institutional Alpha Reporting Systems That Reward Optimism.",
    "outputPath": "/assets/downloads/institutional-alpha-reporting-systems-that-reward-optimism.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-reporting-systems-that-reward-optimismpdf",
    "categorySlug": "institutional-alpha-reporting-systems-that-reward-optimismpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49669,
    "fileSizeHuman": "48.5 KB",
    "lastModified": "2026-05-09T02:06:37.200Z",
    "md5": "41f7fd952af8afe946ff5c7641839c3e",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-signal-decay-in-reporting-chains",
    "title": "Institutional Alpha Signal Decay In Reporting Chains",
    "description": "Institutional Alpha Signal Decay In Reporting Chains — Abraham of London resource.",
    "excerpt": "Institutional Alpha Signal Decay In Reporting Chains.",
    "outputPath": "/assets/downloads/institutional-alpha-signal-decay-in-reporting-chains.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-signal-decay-in-reporting-chainspdf",
    "categorySlug": "institutional-alpha-signal-decay-in-reporting-chainspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49050,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:37.202Z",
    "md5": "81b85957b52a5e73af9229ec16223020",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-blindness-of-clean-narratives",
    "title": "Institutional Alpha The Blindness Of Clean Narratives",
    "description": "Institutional Alpha The Blindness Of Clean Narratives — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Blindness Of Clean Narratives.",
    "outputPath": "/assets/downloads/institutional-alpha-the-blindness-of-clean-narratives.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-blindness-of-clean-narrativespdf",
    "categorySlug": "institutional-alpha-the-blindness-of-clean-narrativespdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48921,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:37.221Z",
    "md5": "47d9b427dd3b8596e9eb9e2fa65e4f45",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-breakdown-of-field-intelligence",
    "title": "Institutional Alpha The Breakdown Of Field Intelligence",
    "description": "Institutional Alpha The Breakdown Of Field Intelligence — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Breakdown Of Field Intelligence.",
    "outputPath": "/assets/downloads/institutional-alpha-the-breakdown-of-field-intelligence.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-breakdown-of-field-intelligencepdf",
    "categorySlug": "institutional-alpha-the-breakdown-of-field-intelligencepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49727,
    "fileSizeHuman": "48.6 KB",
    "lastModified": "2026-05-09T02:06:39.066Z",
    "md5": "3a1d3ed68d4b1f73ea8cdeb654beee80",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-comfort-of-lagging-indicators",
    "title": "Institutional Alpha The Comfort Of Lagging Indicators",
    "description": "Institutional Alpha The Comfort Of Lagging Indicators — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Comfort Of Lagging Indicators.",
    "outputPath": "/assets/downloads/institutional-alpha-the-comfort-of-lagging-indicators.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-comfort-of-lagging-indicatorspdf",
    "categorySlug": "institutional-alpha-the-comfort-of-lagging-indicatorspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49226,
    "fileSizeHuman": "48.1 KB",
    "lastModified": "2026-05-09T02:06:39.078Z",
    "md5": "b568572d5c813794d3f160edc88a459b",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-danger-of-unaudited-assumptions",
    "title": "Institutional Alpha The Danger Of Unaudited Assumptions",
    "description": "Institutional Alpha The Danger Of Unaudited Assumptions — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Danger Of Unaudited Assumptions.",
    "outputPath": "/assets/downloads/institutional-alpha-the-danger-of-unaudited-assumptions.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-danger-of-unaudited-assumptionspdf",
    "categorySlug": "institutional-alpha-the-danger-of-unaudited-assumptionspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49051,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:39.056Z",
    "md5": "f507421ae902c830ccd1f49b67d6007f",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-difference-between-insight-and-surveillance",
    "title": "Institutional Alpha The Difference Between Insight And Surveillance",
    "description": "Institutional Alpha The Difference Between Insight And Surveillance — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Difference Between Insight And Surveillance.",
    "outputPath": "/assets/downloads/institutional-alpha-the-difference-between-insight-and-surveillance.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-difference-between-insight-and-surveillancepdf",
    "categorySlug": "institutional-alpha-the-difference-between-insight-and-surveillancepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49965,
    "fileSizeHuman": "48.8 KB",
    "lastModified": "2026-05-09T02:06:39.060Z",
    "md5": "bafa6101fc7ea0dec87d9da2a0f6e484",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-discipline-of-decision-grade-intelligence",
    "title": "Institutional Alpha The Discipline Of Decision Grade Intelligence",
    "description": "Institutional Alpha The Discipline Of Decision Grade Intelligence — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Discipline Of Decision Grade Intelligence.",
    "outputPath": "/assets/downloads/institutional-alpha-the-discipline-of-decision-grade-intelligence.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-discipline-of-decision-grade-intelligencepdf",
    "categorySlug": "institutional-alpha-the-discipline-of-decision-grade-intelligencepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49995,
    "fileSizeHuman": "48.8 KB",
    "lastModified": "2026-05-09T02:06:41.027Z",
    "md5": "63c497dff02b7d42d549036b0b4921d8",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-hidden-cost-of-flattering-data",
    "title": "Institutional Alpha The Hidden Cost Of Flattering Data",
    "description": "Institutional Alpha The Hidden Cost Of Flattering Data — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Hidden Cost Of Flattering Data.",
    "outputPath": "/assets/downloads/institutional-alpha-the-hidden-cost-of-flattering-data.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-hidden-cost-of-flattering-datapdf",
    "categorySlug": "institutional-alpha-the-hidden-cost-of-flattering-datapdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49888,
    "fileSizeHuman": "48.7 KB",
    "lastModified": "2026-05-09T02:06:41.017Z",
    "md5": "966d243254ad24fbfbd8072eb7746607",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-institutional-price-of-guesswork",
    "title": "Institutional Alpha The Institutional Price Of Guesswork",
    "description": "Institutional Alpha The Institutional Price Of Guesswork — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Institutional Price Of Guesswork.",
    "outputPath": "/assets/downloads/institutional-alpha-the-institutional-price-of-guesswork.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-institutional-price-of-guessworkpdf",
    "categorySlug": "institutional-alpha-the-institutional-price-of-guessworkpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48983,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:41.031Z",
    "md5": "35b9287954d2a21a1a0c473aef5e5d90",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-the-politics-of-suppressed-bad-news",
    "title": "Institutional Alpha The Politics Of Suppressed Bad News",
    "description": "Institutional Alpha The Politics Of Suppressed Bad News — Abraham of London resource.",
    "excerpt": "Institutional Alpha The Politics Of Suppressed Bad News.",
    "outputPath": "/assets/downloads/institutional-alpha-the-politics-of-suppressed-bad-news.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-the-politics-of-suppressed-bad-newspdf",
    "categorySlug": "institutional-alpha-the-politics-of-suppressed-bad-newspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49317,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:41.019Z",
    "md5": "8b35cad56e602d66fef65305e9c8b453",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-weak-signals-before-reputational-fracture",
    "title": "Institutional Alpha Weak Signals Before Reputational Fracture",
    "description": "Institutional Alpha Weak Signals Before Reputational Fracture — Abraham of London resource.",
    "excerpt": "Institutional Alpha Weak Signals Before Reputational Fracture.",
    "outputPath": "/assets/downloads/institutional-alpha-weak-signals-before-reputational-fracture.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-weak-signals-before-reputational-fracturepdf",
    "categorySlug": "institutional-alpha-weak-signals-before-reputational-fracturepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49685,
    "fileSizeHuman": "48.5 KB",
    "lastModified": "2026-05-09T02:06:42.855Z",
    "md5": "784a18bf69317726e400bc0de7a93584",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-when-analysts-inherit-a-broken-mandate",
    "title": "Institutional Alpha When Analysts Inherit A Broken Mandate",
    "description": "Institutional Alpha When Analysts Inherit A Broken Mandate — Abraham of London resource.",
    "excerpt": "Institutional Alpha When Analysts Inherit A Broken Mandate.",
    "outputPath": "/assets/downloads/institutional-alpha-when-analysts-inherit-a-broken-mandate.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-when-analysts-inherit-a-broken-mandatepdf",
    "categorySlug": "institutional-alpha-when-analysts-inherit-a-broken-mandatepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50083,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:42.855Z",
    "md5": "946b6db537998ea75c57aac889a4fd3a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-when-dashboards-outpace-judgment",
    "title": "Institutional Alpha When Dashboards Outpace Judgment",
    "description": "Institutional Alpha When Dashboards Outpace Judgment — Abraham of London resource.",
    "excerpt": "Institutional Alpha When Dashboards Outpace Judgment.",
    "outputPath": "/assets/downloads/institutional-alpha-when-dashboards-outpace-judgment.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-when-dashboards-outpace-judgmentpdf",
    "categorySlug": "institutional-alpha-when-dashboards-outpace-judgmentpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49474,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:42.882Z",
    "md5": "564ec961949a39c516cf816560ad0b7c",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-when-risk-travels-faster-than-reporting",
    "title": "Institutional Alpha When Risk Travels Faster Than Reporting",
    "description": "Institutional Alpha When Risk Travels Faster Than Reporting — Abraham of London resource.",
    "excerpt": "Institutional Alpha When Risk Travels Faster Than Reporting.",
    "outputPath": "/assets/downloads/institutional-alpha-when-risk-travels-faster-than-reporting.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-when-risk-travels-faster-than-reportingpdf",
    "categorySlug": "institutional-alpha-when-risk-travels-faster-than-reportingpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50389,
    "fileSizeHuman": "49.2 KB",
    "lastModified": "2026-05-09T02:06:42.864Z",
    "md5": "15b35acf57149a1ab45aad126fbf57df",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-when-scenario-planning-becomes-theatre",
    "title": "Institutional Alpha When Scenario Planning Becomes Theatre",
    "description": "Institutional Alpha When Scenario Planning Becomes Theatre — Abraham of London resource.",
    "excerpt": "Institutional Alpha When Scenario Planning Becomes Theatre.",
    "outputPath": "/assets/downloads/institutional-alpha-when-scenario-planning-becomes-theatre.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-when-scenario-planning-becomes-theatrepdf",
    "categorySlug": "institutional-alpha-when-scenario-planning-becomes-theatrepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49494,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:44.778Z",
    "md5": "65c62da6fb73071cd13e3dc55e59807a",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-when-the-board-sees-a-different-company",
    "title": "Institutional Alpha When The Board Sees A Different Company",
    "description": "Institutional Alpha When The Board Sees A Different Company — Abraham of London resource.",
    "excerpt": "Institutional Alpha When The Board Sees A Different Company.",
    "outputPath": "/assets/downloads/institutional-alpha-when-the-board-sees-a-different-company.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-when-the-board-sees-a-different-companypdf",
    "categorySlug": "institutional-alpha-when-the-board-sees-a-different-companypdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49990,
    "fileSizeHuman": "48.8 KB",
    "lastModified": "2026-05-09T02:06:44.781Z",
    "md5": "aa385410ebaefd914c5391b3f8e7fe0e",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-why-executive-summaries-mislead",
    "title": "Institutional Alpha Why Executive Summaries Mislead",
    "description": "Institutional Alpha Why Executive Summaries Mislead — Abraham of London resource.",
    "excerpt": "Institutional Alpha Why Executive Summaries Mislead.",
    "outputPath": "/assets/downloads/institutional-alpha-why-executive-summaries-mislead.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-why-executive-summaries-misleadpdf",
    "categorySlug": "institutional-alpha-why-executive-summaries-misleadpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49031,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:44.790Z",
    "md5": "1845cdc4f1a61ae92089fa10e7d296da",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-alpha-why-leaders-stop-hearing-reality",
    "title": "Institutional Alpha Why Leaders Stop Hearing Reality",
    "description": "Institutional Alpha Why Leaders Stop Hearing Reality — Abraham of London resource.",
    "excerpt": "Institutional Alpha Why Leaders Stop Hearing Reality.",
    "outputPath": "/assets/downloads/institutional-alpha-why-leaders-stop-hearing-reality.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-alpha-why-leaders-stop-hearing-realitypdf",
    "categorySlug": "institutional-alpha-why-leaders-stop-hearing-realitypdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49329,
    "fileSizeHuman": "48.2 KB",
    "lastModified": "2026-05-09T02:06:44.785Z",
    "md5": "5c050b3e1126c2d94e489b39ce6cc298",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "institutional-integrity-audit",
    "title": "Institutional Integrity Audit",
    "description": "Institutional Integrity Audit — Abraham of London resource.",
    "excerpt": "Institutional Integrity Audit.",
    "outputPath": "/assets/downloads/institutional-integrity-audit.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "institutional-integrity-auditpdf",
    "categorySlug": "institutional-integrity-auditpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 82628,
    "fileSizeHuman": "80.7 KB",
    "lastModified": "2026-05-09T02:06:46.943Z",
    "md5": "df5d10d0470bf5f46653a4715f7f9354",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-alignment-without-sovereignty",
    "title": "Sovereign Intelligence Alignment Without Sovereignty",
    "description": "Sovereign Intelligence Alignment Without Sovereignty — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Alignment Without Sovereignty.",
    "outputPath": "/assets/downloads/sovereign-intelligence-alignment-without-sovereignty.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-alignment-without-sovereigntypdf",
    "categorySlug": "sovereign-intelligence-alignment-without-sovereigntypdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48992,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:46.933Z",
    "md5": "23f1f235533119d07fe32c71a8de5051",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-control-without-ownership",
    "title": "Sovereign Intelligence Control Without Ownership",
    "description": "Sovereign Intelligence Control Without Ownership — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Control Without Ownership.",
    "outputPath": "/assets/downloads/sovereign-intelligence-control-without-ownership.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-control-without-ownershippdf",
    "categorySlug": "sovereign-intelligence-control-without-ownershippdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 48931,
    "fileSizeHuman": "47.8 KB",
    "lastModified": "2026-05-09T02:06:46.928Z",
    "md5": "7b1e9613b5c3f34240f61dc4e0d2c06c",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-dependence-disguised-as-partnership",
    "title": "Sovereign Intelligence Dependence Disguised As Partnership",
    "description": "Sovereign Intelligence Dependence Disguised As Partnership — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Dependence Disguised As Partnership.",
    "outputPath": "/assets/downloads/sovereign-intelligence-dependence-disguised-as-partnership.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-dependence-disguised-as-partnershippdf",
    "categorySlug": "sovereign-intelligence-dependence-disguised-as-partnershippdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49041,
    "fileSizeHuman": "47.9 KB",
    "lastModified": "2026-05-09T02:06:46.931Z",
    "md5": "7afa741e39a62011da3182be38d8fe84",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-fragile-autonomy-in-capital-dependent-firms",
    "title": "Sovereign Intelligence Fragile Autonomy In Capital Dependent Firms",
    "description": "Sovereign Intelligence Fragile Autonomy In Capital Dependent Firms — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Fragile Autonomy In Capital Dependent Firms.",
    "outputPath": "/assets/downloads/sovereign-intelligence-fragile-autonomy-in-capital-dependent-firms.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-fragile-autonomy-in-capital-dependent-firmspdf",
    "categorySlug": "sovereign-intelligence-fragile-autonomy-in-capital-dependent-firmspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50314,
    "fileSizeHuman": "49.1 KB",
    "lastModified": "2026-05-09T02:06:48.634Z",
    "md5": "36778357e11cbd5aa6b44de772dba5ca",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-identity-drift-in-institutions-under-external-pressure",
    "title": "Sovereign Intelligence Identity Drift In Institutions Under External Pressure",
    "description": "Sovereign Intelligence Identity Drift In Institutions Under External Pressure — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Identity Drift In Institutions Under External Pressure.",
    "outputPath": "/assets/downloads/sovereign-intelligence-identity-drift-in-institutions-under-external-pressure.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-identity-drift-in-institutions-under-external-pressurepdf",
    "categorySlug": "sovereign-intelligence-identity-drift-in-institutions-under-external-pressurepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 51129,
    "fileSizeHuman": "49.9 KB",
    "lastModified": "2026-05-09T02:06:48.640Z",
    "md5": "262f5030a13d432c479f2e18d21f209d",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-internal-empires-and-the-loss-of-common-rule",
    "title": "Sovereign Intelligence Internal Empires And The Loss Of Common Rule",
    "description": "Sovereign Intelligence Internal Empires And The Loss Of Common Rule — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Internal Empires And The Loss Of Common Rule.",
    "outputPath": "/assets/downloads/sovereign-intelligence-internal-empires-and-the-loss-of-common-rule.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-internal-empires-and-the-loss-of-common-rulepdf",
    "categorySlug": "sovereign-intelligence-internal-empires-and-the-loss-of-common-rulepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50120,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:48.631Z",
    "md5": "6473022dfa6ed65970f018923a12d884",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-pricing-power-as-a-test-of-institutional-freedom",
    "title": "Sovereign Intelligence Pricing Power As A Test Of Institutional Freedom",
    "description": "Sovereign Intelligence Pricing Power As A Test Of Institutional Freedom — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Pricing Power As A Test Of Institutional Freedom.",
    "outputPath": "/assets/downloads/sovereign-intelligence-pricing-power-as-a-test-of-institutional-freedom.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-pricing-power-as-a-test-of-institutional-freedompdf",
    "categorySlug": "sovereign-intelligence-pricing-power-as-a-test-of-institutional-freedompdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50818,
    "fileSizeHuman": "49.6 KB",
    "lastModified": "2026-05-09T02:06:48.636Z",
    "md5": "511a23844ebe364f3079230669fca9b5",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-sovereignty-at-the-edge-of-regulation",
    "title": "Sovereign Intelligence Sovereignty At The Edge Of Regulation",
    "description": "Sovereign Intelligence Sovereignty At The Edge Of Regulation — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Sovereignty At The Edge Of Regulation.",
    "outputPath": "/assets/downloads/sovereign-intelligence-sovereignty-at-the-edge-of-regulation.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-sovereignty-at-the-edge-of-regulationpdf",
    "categorySlug": "sovereign-intelligence-sovereignty-at-the-edge-of-regulationpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50092,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:50.381Z",
    "md5": "d350a9b72318b6df8a38ee721a56675b",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-strategic-ambition-without-sovereign-capacity",
    "title": "Sovereign Intelligence Strategic Ambition Without Sovereign Capacity",
    "description": "Sovereign Intelligence Strategic Ambition Without Sovereign Capacity — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Strategic Ambition Without Sovereign Capacity.",
    "outputPath": "/assets/downloads/sovereign-intelligence-strategic-ambition-without-sovereign-capacity.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-strategic-ambition-without-sovereign-capacitypdf",
    "categorySlug": "sovereign-intelligence-strategic-ambition-without-sovereign-capacitypdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50268,
    "fileSizeHuman": "49.1 KB",
    "lastModified": "2026-05-09T02:06:50.375Z",
    "md5": "61a7d3fa2edb287353ceb9f212883659",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-strategic-exposure-without-red-lines",
    "title": "Sovereign Intelligence Strategic Exposure Without Red Lines",
    "description": "Sovereign Intelligence Strategic Exposure Without Red Lines — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Strategic Exposure Without Red Lines.",
    "outputPath": "/assets/downloads/sovereign-intelligence-strategic-exposure-without-red-lines.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-strategic-exposure-without-red-linespdf",
    "categorySlug": "sovereign-intelligence-strategic-exposure-without-red-linespdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49782,
    "fileSizeHuman": "48.6 KB",
    "lastModified": "2026-05-09T02:06:50.379Z",
    "md5": "b6d03ce116ec4d934897f556ca1358a5",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-cost-of-borrowed-legitimacy",
    "title": "Sovereign Intelligence The Cost Of Borrowed Legitimacy",
    "description": "Sovereign Intelligence The Cost Of Borrowed Legitimacy — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Cost Of Borrowed Legitimacy.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-cost-of-borrowed-legitimacy.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-cost-of-borrowed-legitimacypdf",
    "categorySlug": "sovereign-intelligence-the-cost-of-borrowed-legitimacypdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50088,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:50.373Z",
    "md5": "6499d1f1c9332eeadf5b51e9bef94bc5",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-discipline-of-institutional-self-government",
    "title": "Sovereign Intelligence The Discipline Of Institutional Self Government",
    "description": "Sovereign Intelligence The Discipline Of Institutional Self Government — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Discipline Of Institutional Self Government.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-discipline-of-institutional-self-government.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-discipline-of-institutional-self-governmentpdf",
    "categorySlug": "sovereign-intelligence-the-discipline-of-institutional-self-governmentpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50468,
    "fileSizeHuman": "49.3 KB",
    "lastModified": "2026-05-09T02:06:52.015Z",
    "md5": "1b8aadf22966e7e3dead67dc723bd0b9",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-false-safety-of-strategic-silence",
    "title": "Sovereign Intelligence The False Safety Of Strategic Silence",
    "description": "Sovereign Intelligence The False Safety Of Strategic Silence — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The False Safety Of Strategic Silence.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-false-safety-of-strategic-silence.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-false-safety-of-strategic-silencepdf",
    "categorySlug": "sovereign-intelligence-the-false-safety-of-strategic-silencepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50275,
    "fileSizeHuman": "49.1 KB",
    "lastModified": "2026-05-09T02:06:52.023Z",
    "md5": "a02a91a8898df2ab960ab077f724b104",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-geography-of-hidden-influence",
    "title": "Sovereign Intelligence The Geography Of Hidden Influence",
    "description": "Sovereign Intelligence The Geography Of Hidden Influence — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Geography Of Hidden Influence.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-geography-of-hidden-influence.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-geography-of-hidden-influencepdf",
    "categorySlug": "sovereign-intelligence-the-geography-of-hidden-influencepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50069,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:52.021Z",
    "md5": "4533cc173aba252b1f3a07813eea920b",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-governance-cost-of-permanent-exception",
    "title": "Sovereign Intelligence The Governance Cost Of Permanent Exception",
    "description": "Sovereign Intelligence The Governance Cost Of Permanent Exception — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Governance Cost Of Permanent Exception.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-governance-cost-of-permanent-exception.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-governance-cost-of-permanent-exceptionpdf",
    "categorySlug": "sovereign-intelligence-the-governance-cost-of-permanent-exceptionpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49500,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:52.015Z",
    "md5": "a5f5f2a067758974bcb1ba4bb20da560",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-illusion-of-neutral-platforms",
    "title": "Sovereign Intelligence The Illusion Of Neutral Platforms",
    "description": "Sovereign Intelligence The Illusion Of Neutral Platforms — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Illusion Of Neutral Platforms.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-illusion-of-neutral-platforms.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-illusion-of-neutral-platformspdf",
    "categorySlug": "sovereign-intelligence-the-illusion-of-neutral-platformspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49500,
    "fileSizeHuman": "48.3 KB",
    "lastModified": "2026-05-09T02:06:53.702Z",
    "md5": "1eb198a1b90ae1725558962dfb9484ef",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_48KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-price-of-letting-others-set-your-time-horizon",
    "title": "Sovereign Intelligence The Price Of Letting Others Set Your Time Horizon",
    "description": "Sovereign Intelligence The Price Of Letting Others Set Your Time Horizon — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Price Of Letting Others Set Your Time Horizon.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-price-of-letting-others-set-your-time-horizon.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-price-of-letting-others-set-your-time-horizonpdf",
    "categorySlug": "sovereign-intelligence-the-price-of-letting-others-set-your-time-horizonpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 51069,
    "fileSizeHuman": "49.9 KB",
    "lastModified": "2026-05-09T02:06:53.714Z",
    "md5": "10e9b0b57455e3964e07f11de37b4de7",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-strategic-consequence-of-weak-exit-paths",
    "title": "Sovereign Intelligence The Strategic Consequence Of Weak Exit Paths",
    "description": "Sovereign Intelligence The Strategic Consequence Of Weak Exit Paths — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Strategic Consequence Of Weak Exit Paths.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-strategic-consequence-of-weak-exit-paths.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-strategic-consequence-of-weak-exit-pathspdf",
    "categorySlug": "sovereign-intelligence-the-strategic-consequence-of-weak-exit-pathspdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50788,
    "fileSizeHuman": "49.6 KB",
    "lastModified": "2026-05-09T02:06:53.714Z",
    "md5": "cfb9b9c06132746116cb71afeec28666",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-strategic-risk-of-needing-everyone-to-like-you",
    "title": "Sovereign Intelligence The Strategic Risk Of Needing Everyone To Like You",
    "description": "Sovereign Intelligence The Strategic Risk Of Needing Everyone To Like You — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Strategic Risk Of Needing Everyone To Like You.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-strategic-risk-of-needing-everyone-to-like-you.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-strategic-risk-of-needing-everyone-to-like-youpdf",
    "categorySlug": "sovereign-intelligence-the-strategic-risk-of-needing-everyone-to-like-youpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 51081,
    "fileSizeHuman": "49.9 KB",
    "lastModified": "2026-05-09T02:06:53.721Z",
    "md5": "c71d153bec00d6c844e56e71d876ee97",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-tax-of-strategic-appeasement",
    "title": "Sovereign Intelligence The Tax Of Strategic Appeasement",
    "description": "Sovereign Intelligence The Tax Of Strategic Appeasement — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Tax Of Strategic Appeasement.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-tax-of-strategic-appeasement.pdf",
    "type": "strategic",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-tax-of-strategic-appeasementpdf",
    "categorySlug": "sovereign-intelligence-the-tax-of-strategic-appeasementpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50123,
    "fileSizeHuman": "48.9 KB",
    "lastModified": "2026-05-09T02:06:55.529Z",
    "md5": "7428186835f75f37d43b39b755103bce",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-vulnerability-of-narrative-capture",
    "title": "Sovereign Intelligence The Vulnerability Of Narrative Capture",
    "description": "Sovereign Intelligence The Vulnerability Of Narrative Capture — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Vulnerability Of Narrative Capture.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-vulnerability-of-narrative-capture.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-vulnerability-of-narrative-capturepdf",
    "categorySlug": "sovereign-intelligence-the-vulnerability-of-narrative-capturepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49861,
    "fileSizeHuman": "48.7 KB",
    "lastModified": "2026-05-09T02:06:55.522Z",
    "md5": "2fc40df866a42b913084a1e4f37a5faa",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-the-weakness-of-outsourced-judgment",
    "title": "Sovereign Intelligence The Weakness Of Outsourced Judgment",
    "description": "Sovereign Intelligence The Weakness Of Outsourced Judgment — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence The Weakness Of Outsourced Judgment.",
    "outputPath": "/assets/downloads/sovereign-intelligence-the-weakness-of-outsourced-judgment.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-the-weakness-of-outsourced-judgmentpdf",
    "categorySlug": "sovereign-intelligence-the-weakness-of-outsourced-judgmentpdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49940,
    "fileSizeHuman": "48.8 KB",
    "lastModified": "2026-05-09T02:06:55.528Z",
    "md5": "269b967b38078c546490c3d15438c66b",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-when-institutions-become-too-easy-to-pressure",
    "title": "Sovereign Intelligence When Institutions Become Too Easy To Pressure",
    "description": "Sovereign Intelligence When Institutions Become Too Easy To Pressure — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence When Institutions Become Too Easy To Pressure.",
    "outputPath": "/assets/downloads/sovereign-intelligence-when-institutions-become-too-easy-to-pressure.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-when-institutions-become-too-easy-to-pressurepdf",
    "categorySlug": "sovereign-intelligence-when-institutions-become-too-easy-to-pressurepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49897,
    "fileSizeHuman": "48.7 KB",
    "lastModified": "2026-05-09T02:06:55.525Z",
    "md5": "53f75f85895162c3c2bcffd89e9f9d0e",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-when-optionality-quietly-dies",
    "title": "Sovereign Intelligence When Optionality Quietly Dies",
    "description": "Sovereign Intelligence When Optionality Quietly Dies — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence When Optionality Quietly Dies.",
    "outputPath": "/assets/downloads/sovereign-intelligence-when-optionality-quietly-dies.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-when-optionality-quietly-diespdf",
    "categorySlug": "sovereign-intelligence-when-optionality-quietly-diespdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 49915,
    "fileSizeHuman": "48.7 KB",
    "lastModified": "2026-05-09T02:06:56.837Z",
    "md5": "c25701a9f67f27963d7194be03f11636",
    "version": "1.0.0",
    "qualityFlag": "SMALL_PDF_49KB",
    "priority": 10,
    "preload": false
  },
  {
    "id": "sovereign-intelligence-why-power-concentrates-around-the-decisive",
    "title": "Sovereign Intelligence Why Power Concentrates Around The Decisive",
    "description": "Sovereign Intelligence Why Power Concentrates Around The Decisive — Abraham of London resource.",
    "excerpt": "Sovereign Intelligence Why Power Concentrates Around The Decisive.",
    "outputPath": "/assets/downloads/sovereign-intelligence-why-power-concentrates-around-the-decisive.pdf",
    "type": "tool",
    "format": "PDF",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "category": "sovereign-intelligence-why-power-concentrates-around-the-decisivepdf",
    "categorySlug": "sovereign-intelligence-why-power-concentrates-around-the-decisivepdf",
    "isFillable": false,
    "isInteractive": false,
    "requiresAuth": false,
    "exists": true,
    "fileSizeBytes": 50877,
    "fileSizeHuman": "49.7 KB",
    "lastModified": "2026-05-09T02:06:56.852Z",
    "md5": "7e8f2ece3ddcebaa8cbe9ba04cddc97f",
    "version": "1.0.0",
    "qualityFlag": null,
    "priority": 10,
    "preload": false
  }
];
export const GENERATED_AT = "2026-05-20T18:43:45.452Z";
export const GENERATED_COUNT = 83;
