/** AUTO-GENERATED - DO NOT EDIT */
export const GENERATED_PDF_CONFIGS = [
  {
    "id": "abraham-vault-pack",
    "title": "Abraham Vault Pack",
    "type": "bundle",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/abraham-vault-pack.pdf",
    "category": "vault",
    "description": "Comprehensive vault pack with foundational resources",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.864Z",
    "fileSizeBytes": 2023
  },
  {
    "id": "board-decision-log-template",
    "title": "Board Decision Log Template",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/board-decision-log-template.pdf",
    "category": "governance",
    "description": "Template for tracking board decisions and resolutions",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:20.268Z",
    "fileSizeBytes": 926
  },
  {
    "id": "board-investor-onepager",
    "title": "Board Investor One-Pager",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/board-investor-onepager.pdf",
    "category": "governance",
    "description": "One-page summary for board and investor communications",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:07:10.299Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "brotherhood-covenant",
    "title": "Brotherhood Covenant",
    "type": "framework",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/brotherhood-covenant.pdf",
    "category": "leadership",
    "description": "Covenant framework for brotherhood and fellowship",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:07:27.780Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "brotherhood-leader-guide",
    "title": "Brotherhood Leader Guide",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/brotherhood-leader-guide.pdf",
    "category": "leadership",
    "description": "Guide for leading brotherhood groups and communities",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:41:48.621Z",
    "fileSizeBytes": 264122
  },
  {
    "id": "brotherhood-starter-kit",
    "title": "Brotherhood Starter Kit",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/brotherhood-starter-kit.pdf",
    "category": "leadership",
    "description": "Starter kit for establishing brotherhood groups",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:40:50.282Z",
    "fileSizeBytes": 353980
  },
  {
    "id": "canon-volume-iv-diagnostic-toolkit",
    "title": "Canon Volume IV Diagnostic Toolkit",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-iv-diagnostic-toolkit.pdf",
    "category": "canon",
    "description": "Diagnostic tools from Canon Volume IV",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:07:37.292Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "canon-volume-v-governance-diagnostic-toolkit",
    "title": "Canon Volume V Governance Diagnostic Toolkit",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-v-governance-diagnostic-toolkit.pdf",
    "category": "governance",
    "description": "Governance diagnostic tools from Canon Volume V",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:07:50.588Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "communication-script-bpf",
    "title": "Communication Script (BPF)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/communication-script-bpf.pdf",
    "category": "leadership",
    "description": "Business Process Framework communication script",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:07:56.964Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "core-alignment",
    "title": "Core Alignment Framework",
    "type": "framework",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/core-alignment.pdf",
    "category": "personal-growth",
    "description": "Framework for aligning with core values and purpose",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.879Z",
    "fileSizeBytes": 94161
  },
  {
    "id": "core-legacy",
    "title": "Core Legacy Framework",
    "type": "framework",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/core-legacy.pdf",
    "category": "legacy",
    "description": "Framework for building and sustaining legacy",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.893Z",
    "fileSizeBytes": 10765
  },
  {
    "id": "decision-log-template",
    "title": "Decision Log Template",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/decision-log-template.pdf",
    "category": "operations",
    "description": "Template for logging and tracking decisions",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:06.256Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "decision-matrix-scorecard",
    "title": "Decision Matrix Scorecard",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/decision-matrix-scorecard.pdf",
    "category": "operations",
    "description": "Scorecard for decision matrix evaluation",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:12.231Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "download-legacy-architecture-canvas",
    "title": "Legacy Architecture Canvas",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/download-legacy-architecture-canvas.pdf",
    "category": "legacy",
    "description": "Canvas for designing legacy architecture",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:26.531Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "entrepreneur-operating-pack",
    "title": "Entrepreneur Operating Pack",
    "type": "pack",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-operating-pack.pdf",
    "category": "operations",
    "description": "Operating pack for entrepreneurs",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:40.950Z",
    "fileSizeBytes": 929
  },
  {
    "id": "entrepreneur-survival-checklist",
    "title": "Entrepreneur Survival Checklist",
    "type": "checklist",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-survival-checklist.pdf",
    "category": "operations",
    "description": "Checklist for entrepreneurial survival and resilience",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:46.897Z",
    "fileSizeBytes": 933
  },
  {
    "id": "family-altar-liturgy",
    "title": "Family Altar Liturgy",
    "type": "liturgy",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/family-altar-liturgy.pdf",
    "category": "theology",
    "description": "Liturgy for family altar and worship",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:52.957Z",
    "fileSizeBytes": 922
  },
  {
    "id": "fathers-family-court-pack",
    "title": "Family Court Practical Pack",
    "type": "bundle",
    "tier": "member",
    "outputPath": "/assets/downloads/fathers-family-court-pack.pdf",
    "requiresAuth": true,
    "category": "family-court",
    "description": "Practical resources for family court proceedings",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:39:09.141Z",
    "fileSizeBytes": 276382
  },
  {
    "id": "leaders-cue-card-two-up",
    "title": "Leaders Cue Card (Two-Up)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/leaders-cue-card-two-up.pdf",
    "category": "leadership",
    "description": "Two-up cue card for leaders",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:58.889Z",
    "fileSizeBytes": 925
  },
  {
    "id": "leadership-playbook",
    "title": "Leadership Playbook",
    "type": "playbook",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/leadership-playbook.pdf",
    "category": "leadership",
    "description": "Comprehensive leadership playbook",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:04.966Z",
    "fileSizeBytes": 921
  },
  {
    "id": "legacy-canvas",
    "title": "Legacy Canvas",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/legacy-canvas.pdf",
    "category": "legacy",
    "description": "Canvas for legacy planning and design",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:10.042Z",
    "fileSizeBytes": 915
  },
  {
    "id": "legacy-architecture-canvas",
    "title": "Legacy Architecture Canvas",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/legacy-architecture-canvas.pdf",
    "category": "legacy",
    "description": "High-fidelity legacy architecture canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-05T14:19:45.482Z",
    "fileSizeBytes": 1189632
  },
  {
    "id": "life-alignment-assessment",
    "title": "Life Alignment Assessment",
    "type": "assessment",
    "tier": "free",
    "outputPath": "/assets/downloads/life-alignment-assessment.pdf",
    "category": "personal-growth",
    "description": "Assessment for life alignment and purpose discovery",
    "preload": true,
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:15.160Z",
    "fileSizeBytes": 927
  },
  {
    "id": "mentorship-starter-kit",
    "title": "Mentorship Starter Kit",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/mentorship-starter-kit.pdf",
    "category": "leadership",
    "description": "Starter kit for mentorship relationships",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:20.212Z",
    "fileSizeBytes": 924
  },
  {
    "id": "operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "type": "pack",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/operating-cadence-pack.pdf",
    "category": "operations",
    "description": "Pack for establishing operating cadence",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:26.947Z",
    "fileSizeBytes": 925
  },
  {
    "id": "personal-alignment-assessment-fillable",
    "title": "Personal Alignment Assessment (Fillable)",
    "type": "assessment",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/personal-alignment-assessment-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "personal-growth",
    "description": "Fillable assessment for personal alignment",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:32.047Z",
    "fileSizeBytes": 935
  },
  {
    "id": "principles-for-my-son",
    "title": "Principles for My Son",
    "type": "editorial",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son.pdf",
    "category": "family",
    "description": "Editorial on principles for raising sons",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:35.540Z",
    "fileSizeBytes": 923
  },
  {
    "id": "principles-for-my-son-cue-card",
    "title": "Principles for My Son (Cue Card)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son-cue-card.pdf",
    "category": "family",
    "description": "Cue card version of principles for sons",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:46.848Z",
    "fileSizeBytes": 932
  },
  {
    "id": "purpose-pyramid-worksheet",
    "title": "Purpose Pyramid Worksheet",
    "type": "worksheet",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/purpose-pyramid-worksheet.pdf",
    "category": "personal-growth",
    "description": "Worksheet for purpose pyramid development",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:51.953Z",
    "fileSizeBytes": 927
  },
  {
    "id": "scripture-track-john14",
    "title": "Scripture Track: John 14",
    "type": "study",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/scripture-track-john14.pdf",
    "category": "theology",
    "description": "Scripture study track for John 14",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:09:57.051Z",
    "fileSizeBytes": 924
  },
  {
    "id": "standards-brief",
    "title": "Standards Brief",
    "type": "brief",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/standards-brief.pdf",
    "category": "leadership",
    "description": "Brief on leadership and operational standards",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:03.276Z",
    "fileSizeBytes": 917
  },
  {
    "id": "surrender-framework",
    "title": "Surrender Framework",
    "type": "framework",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/surrender-framework.pdf",
    "category": "personal-growth",
    "description": "Framework for spiritual and personal surrender",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:09.522Z",
    "fileSizeBytes": 921
  },
  {
    "id": "surrender-principles",
    "title": "Surrender Principles",
    "type": "editorial",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/surrender-principles.pdf",
    "category": "personal-growth",
    "description": "Principles of surrender in life and leadership",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:16.058Z",
    "fileSizeBytes": 922
  },
  {
    "id": "ultimate-purpose-of-man-editorial",
    "title": "Ultimate Purpose of Man (Editorial)",
    "type": "editorial",
    "tier": "free",
    "outputPath": "/assets/downloads/ultimate-purpose-of-man-editorial.pdf",
    "category": "theology",
    "description": "Editorial on the ultimate purpose of man",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:16.091Z",
    "fileSizeBytes": 2435211
  },
  {
    "id": "ultimate-purpose-of-man-editorial-a4-premium-architect",
    "title": "Ultimate Purpose of Man (A4 Premium)",
    "type": "editorial",
    "tier": "architect",
    "outputPath": "/assets/downloads/ultimate-purpose-of-man-editorial-a4-premium-architect.pdf",
    "category": "theology",
    "description": "Premium A4 version of Ultimate Purpose of Man",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:22.458Z",
    "fileSizeBytes": 956
  },
  {
    "id": "weekly-operating-rhythm",
    "title": "Weekly Operating Rhythm",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/weekly-operating-rhythm.pdf",
    "category": "operations",
    "description": "Template for weekly operating rhythm and cadence",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:28.675Z",
    "fileSizeBytes": 925
  },
  {
    "id": "decision-matrix-scorecard-fillable",
    "title": "Decision Matrix Scorecard (Fillable)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/decision-matrix-scorecard-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "operations",
    "description": "Fillable version of decision matrix scorecard",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.970Z",
    "fileSizeBytes": 36611
  },
  {
    "id": "legacy-canvas-fillable",
    "title": "Legacy Canvas (Fillable)",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/legacy-canvas-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "legacy",
    "description": "Fillable version of legacy canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:16.005Z",
    "fileSizeBytes": 10765
  },
  {
    "id": "legacy-architecture-canvas-a3-premium-architect",
    "title": "Legacy Architecture Canvas (A3)",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/legacy-architecture-canvas-a3-premium-architect.pdf",
    "category": "legacy",
    "description": "A3 premium version of legacy architecture canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.997Z",
    "fileSizeBytes": 15255
  },
  {
    "id": "legacy-architecture-canvas-a4-premium-architect",
    "title": "Legacy Architecture Canvas (A4)",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/legacy-architecture-canvas-a4-premium-architect.pdf",
    "category": "legacy",
    "description": "A4 premium version of legacy architecture canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.997Z",
    "fileSizeBytes": 15018
  },
  {
    "id": "legacy-architecture-canvas-letter-premium-architect",
    "title": "Legacy Architecture Canvas (Letter)",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/legacy-architecture-canvas-letter-premium-architect.pdf",
    "category": "legacy",
    "description": "Letter premium version of legacy architecture canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:16.002Z",
    "fileSizeBytes": 14666
  },
  {
    "id": "purpose-pyramid-worksheet-fillable",
    "title": "Purpose Pyramid Worksheet (Fillable)",
    "type": "worksheet",
    "tier": "free",
    "outputPath": "/assets/downloads/purpose-pyramid-worksheet-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "personal-growth",
    "description": "Fillable version of purpose pyramid worksheet",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-28T09:08:16.042Z",
    "fileSizeBytes": 20245
  },
  {
    "id": "lib-brotherhood-leader-guide",
    "title": "Brotherhood Leader Guide (Library)",
    "type": "toolkit",
    "tier": "member",
    "outputPath": "/assets/downloads/lib-pdf/brotherhood-leader-guide.pdf",
    "category": "leadership",
    "description": "Library version of brotherhood leader guide",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:42:13.606Z",
    "fileSizeBytes": 264122
  },
  {
    "id": "lib-brotherhood-starter-kit",
    "title": "Brotherhood Starter Kit (Library)",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/brotherhood-starter-kit.pdf",
    "category": "leadership",
    "description": "Library version of brotherhood starter kit",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:40:29.492Z",
    "fileSizeBytes": 353980
  },
  {
    "id": "lib-decision-log",
    "title": "Decision Log Template (Library)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/decision-log-template.pdf",
    "category": "operations",
    "description": "Library version of decision log template",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:06.256Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "lib-decision-matrix-fillable",
    "title": "Decision Matrix Scorecard (Fillable Library)",
    "type": "tool",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/decision-matrix-scorecard-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "operations",
    "description": "Library fillable version of decision matrix",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.387Z",
    "fileSizeBytes": 36611
  },
  {
    "id": "lib-family-court-pack",
    "title": "Family Court Practical Pack (Library)",
    "type": "bundle",
    "tier": "member",
    "outputPath": "/assets/downloads/lib-pdf/fathers-family-court-pack.pdf",
    "requiresAuth": true,
    "category": "family-court",
    "description": "Library version of family court pack",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:39:41.389Z",
    "fileSizeBytes": 276382
  },
  {
    "id": "lib-legacy-canvas-fillable",
    "title": "Legacy Canvas (Fillable Library)",
    "type": "canvas",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/legacy-canvas-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "legacy",
    "description": "Library fillable version of legacy canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.418Z",
    "fileSizeBytes": 10765
  },
  {
    "id": "lib-life-alignment-assessment-alt",
    "title": "Life Alignment Assessment (Library)",
    "type": "assessment",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/life-alignment-assessment.pdf",
    "category": "personal-growth",
    "description": "Library version of life alignment assessment",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:36.468Z",
    "fileSizeBytes": 935
  },
  {
    "id": "lib-personal-alignment-fillable",
    "title": "Personal Alignment Assessment (Fillable Library)",
    "type": "assessment",
    "tier": "free",
    "outputPath": "/assets/downloads/content-downloads/personal-alignment-assessment-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "personal-growth",
    "description": "Library fillable version of personal alignment",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:32.047Z",
    "fileSizeBytes": 935
  },
  {
    "id": "lib-purpose-pyramid-fillable",
    "title": "Purpose Pyramid Worksheet (Fillable Library)",
    "type": "worksheet",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/purpose-pyramid-worksheet-fillable.pdf",
    "isInteractive": true,
    "isFillable": true,
    "category": "personal-growth",
    "description": "Library fillable version of purpose pyramid",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:38:56.104Z",
    "fileSizeBytes": 20245
  },
  {
    "id": "lib-ultimate-purpose-editorial-alt",
    "title": "Ultimate Purpose of Man (Editorial Library)",
    "type": "editorial",
    "tier": "free",
    "outputPath": "/assets/downloads/lib-pdf/ultimate-purpose-of-man-editorial.pdf",
    "category": "theology",
    "description": "Library version of ultimate purpose editorial",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-01-02T17:18:50.916Z",
    "fileSizeBytes": 2435211
  },
  {
    "id": "res-brotherhood-starter-kit",
    "title": "Brotherhood Starter Kit (Resources)",
    "type": "toolkit",
    "tier": "free",
    "outputPath": "/assets/downloads/public-assets/resources/pdfs/brotherhood-starter-kit.pdf",
    "category": "leadership",
    "description": "Resources version of brotherhood starter kit",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:51.737Z",
    "fileSizeBytes": 929
  },
  {
    "id": "res-destiny-mapping",
    "title": "Destiny Mapping Worksheet",
    "type": "worksheet",
    "tier": "free",
    "outputPath": "/assets/downloads/public-assets/resources/pdfs/destiny-mapping-worksheet.pdf",
    "category": "strategic",
    "description": "Destiny mapping worksheet for strategic planning",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:10:58.000Z",
    "fileSizeBytes": 921
  },
  {
    "id": "res-fatherhood-impact",
    "title": "Fatherhood Impact Framework",
    "type": "framework",
    "tier": "free",
    "outputPath": "/assets/downloads/public-assets/resources/pdfs/fatherhood-impact-framework.pdf",
    "category": "family",
    "description": "Framework for fatherhood impact and legacy",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:02.958Z",
    "fileSizeBytes": 923
  },
  {
    "id": "res-institutional-health",
    "title": "Institutional Health Scorecard",
    "type": "assessment",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/resources/pdfs/institutional-health-scorecard.pdf",
    "category": "governance",
    "description": "Scorecard for institutional health assessment",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:08.723Z",
    "fileSizeBytes": 926
  },
  {
    "id": "res-leadership-blueprint",
    "title": "Leadership Standards Blueprint",
    "type": "blueprint",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/resources/pdfs/leadership-standards-blueprint.pdf",
    "category": "leadership",
    "description": "Blueprint for leadership standards development",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:14.621Z",
    "fileSizeBytes": 926
  },
  {
    "id": "vault-board-decision-log",
    "title": "Board Decision Log (Vault)",
    "type": "tool",
    "tier": "architect",
    "outputPath": "/assets/downloads/content-downloads/board-decision-log-template.pdf",
    "category": "governance",
    "description": "Vault version of board decision log",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:20.268Z",
    "fileSizeBytes": 926
  },
  {
    "id": "vault-decision-log",
    "title": "Decision Log Template (Vault)",
    "type": "tool",
    "tier": "architect",
    "outputPath": "/assets/downloads/content-downloads/decision-log-template.pdf",
    "category": "operations",
    "description": "Vault version of decision log template",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:08:06.256Z",
    "fileSizeBytes": 140609
  },
  {
    "id": "vault-decision-matrix-fillable",
    "title": "Decision Matrix Scorecard (Vault Fillable)",
    "type": "tool",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/decision-matrix-scorecard-fillable.pdf",
    "isFillable": true,
    "category": "operations",
    "description": "Vault fillable version of decision matrix",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.387Z",
    "fileSizeBytes": 36611
  },
  {
    "id": "vault-legacy-canvas-fillable",
    "title": "Legacy Canvas (Vault Fillable)",
    "type": "canvas",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/legacy-canvas-fillable.pdf",
    "isFillable": true,
    "category": "legacy",
    "description": "Vault fillable version of legacy canvas",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.418Z",
    "fileSizeBytes": 10765
  },
  {
    "id": "vault-operating-cadence",
    "title": "Operating Cadence Pack (Vault)",
    "type": "pack",
    "tier": "architect",
    "outputPath": "/assets/downloads/content-downloads/operating-cadence-pack.pdf",
    "category": "operations",
    "description": "Vault version of operating cadence pack",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:26.947Z",
    "fileSizeBytes": 925
  },
  {
    "id": "vault-personal-alignment-fillable",
    "title": "Personal Alignment Assessment (Vault Fillable)",
    "type": "assessment",
    "tier": "architect",
    "outputPath": "/assets/downloads/content-downloads/personal-alignment-assessment-fillable.pdf",
    "isFillable": true,
    "category": "personal-growth",
    "description": "Vault fillable version of personal alignment",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-05T12:11:32.047Z",
    "fileSizeBytes": 935
  },
  {
    "id": "vault-purpose-pyramid-fillable",
    "title": "Purpose Pyramid Worksheet (Vault Fillable)",
    "type": "worksheet",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/purpose-pyramid-worksheet-fillable.pdf",
    "isFillable": true,
    "category": "personal-growth",
    "description": "Vault fillable version of purpose pyramid",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "requiresAuth": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2025-12-28T16:38:56.104Z",
    "fileSizeBytes": 20245
  },
  {
    "id": "vault-lib-brotherhood-leader",
    "title": "Brotherhood Leader Guide (Vault Library)",
    "type": "toolkit",
    "tier": "inner-circle",
    "outputPath": "/vault/downloads/lib-pdf/brotherhood-leader-guide.pdf",
    "requiresAuth": true,
    "category": "leadership",
    "description": "Vault library version of brotherhood leader guide",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:41:48.621Z",
    "fileSizeBytes": 264122
  },
  {
    "id": "vault-lib-brotherhood-starter",
    "title": "Brotherhood Starter Kit (Vault Library)",
    "type": "toolkit",
    "tier": "inner-circle",
    "outputPath": "/vault/downloads/lib-pdf/brotherhood-starter-kit.pdf",
    "requiresAuth": true,
    "category": "leadership",
    "description": "Vault library version of brotherhood starter kit",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:40:50.282Z",
    "fileSizeBytes": 353980
  },
  {
    "id": "vault-lib-family-court-pack",
    "title": "Family Court Practical Pack (Vault Library)",
    "type": "bundle",
    "tier": "inner-circle",
    "outputPath": "/vault/downloads/lib-pdf/fathers-family-court-pack.pdf",
    "requiresAuth": true,
    "category": "family-court",
    "description": "Vault library version of family court pack",
    "format": "PDF",
    "formats": [
      "A4"
    ],
    "isInteractive": false,
    "isFillable": false,
    "version": "1.0.0",
    "author": "Abraham of London",
    "tags": [],
    "exists": true,
    "lastModified": "2026-02-04T17:39:09.141Z",
    "fileSizeBytes": 276382
  },
  {
    "id": "auto__downloads__abraham-vault-pack",
    "title": "Abraham Vault Pack",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/abraham-vault-pack.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.512Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__board-decision-log-template",
    "title": "Board Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/board-decision-log-template.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.512Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__board-decision-log-template",
    "title": "Board Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/board-decision-log-template.xlsx",
    "format": "BINARY",
    "exists": true,
    "lastModified": "2025-12-28T15:53:30.295Z",
    "fileSizeBytes": 8704,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__board-investor-onepager",
    "title": "Board Investor Onepager",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/board-investor-onepager.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.512Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__brotherhood-covenant",
    "title": "Brotherhood Covenant",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/brotherhood-covenant.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.527Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__canon-volume-iv-diagnostic-toolkit",
    "title": "Canon Volume Iv Diagnostic Toolkit",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/canon-volume-iv-diagnostic-toolkit.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.527Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__canon-volume-v-governance-diagnostic-toolkit",
    "title": "Canon Volume V Governance Diagnostic Toolkit",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/canon-volume-v-governance-diagnostic-toolkit.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.527Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__communication-script-bpf",
    "title": "Communication Script Bpf",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/communication-script-bpf.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.537Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__decision-log-template",
    "title": "Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/decision-log-template.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-01-28T09:08:15.967Z",
    "fileSizeBytes": 344232,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__decision-matrix-scorecard",
    "title": "Decision Matrix Scorecard",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/decision-matrix-scorecard.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.541Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__download-legacy-architecture-canvas",
    "title": "Download Legacy Architecture Canvas",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/download-legacy-architecture-canvas.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__entrepreneur-operating-pack",
    "title": "Entrepreneur Operating Pack",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/entrepreneur-operating-pack.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__entrepreneur-survival-checklist",
    "title": "Entrepreneur Survival Checklist",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/entrepreneur-survival-checklist.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__family-altar-liturgy",
    "title": "Family Altar Liturgy",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/family-altar-liturgy.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__leaders-cue-card-two-up",
    "title": "Leaders Cue Card Two Up",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/leaders-cue-card-two-up.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__leadership-playbook",
    "title": "Leadership Playbook",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/leadership-playbook.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__legacy-canvas",
    "title": "Legacy Canvas",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/legacy-canvas.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.543Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__lib-pdf__decision-log-template",
    "title": "Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/lib-pdf/decision-log-template.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.356Z",
    "fileSizeBytes": 344232,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__lib-pdf__personal-alignment-assessment-fillable",
    "title": "Personal Alignment Assessment Fillable",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/lib-pdf/personal-alignment-assessment-fillable.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.577Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__mentorship-starter-kit",
    "title": "Mentorship Starter Kit",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/mentorship-starter-kit.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/operating-cadence-pack.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/operating-cadence-pack.pptx",
    "format": "BINARY",
    "exists": true,
    "lastModified": "2025-12-28T15:59:43.214Z",
    "fileSizeBytes": 142484,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__personal-alignment-assessment-fillable",
    "title": "Personal Alignment Assessment Fillable",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/personal-alignment-assessment-fillable.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__principles-for-my-son-cue-card",
    "title": "Principles For My Son Cue Card",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/principles-for-my-son-cue-card.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__principles-for-my-son",
    "title": "Principles For My Son",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/principles-for-my-son.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__vault__board-decision-log-template",
    "title": "Board Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/board-decision-log-template.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-01-05T14:20:14.916Z",
    "fileSizeBytes": 74855,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__vault__decision-log-template",
    "title": "Decision Log Template",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/decision-log-template.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2025-12-28T16:40:32.356Z",
    "fileSizeBytes": 344232,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__vault__operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/operating-cadence-pack.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-01-05T14:20:18.490Z",
    "fileSizeBytes": 82849,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__vault__personal-alignment-assessment-fillable",
    "title": "Personal Alignment Assessment Fillable",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/public-assets/vault/personal-alignment-assessment-fillable.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.590Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__purpose-pyramid-worksheet",
    "title": "Purpose Pyramid Worksheet",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/purpose-pyramid-worksheet.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.558Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__scripture-track-john14",
    "title": "Scripture Track John14",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/scripture-track-john14.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.574Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__standards-brief",
    "title": "Standards Brief",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/standards-brief.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.574Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  },
  {
    "id": "auto__downloads__weekly-operating-rhythm",
    "title": "Weekly Operating Rhythm",
    "type": "other",
    "tier": "architect",
    "outputPath": "/assets/downloads/weekly-operating-rhythm.pdf",
    "format": "PDF",
    "exists": true,
    "lastModified": "2026-02-05T11:49:42.577Z",
    "fileSizeBytes": 23,
    "category": "unmapped-discovery",
    "version": "1.0.0",
    "requiresAuth": true
  }
] as const;
export const getGeneratedPDFs = () => GENERATED_PDF_CONFIGS;
