// scripts/pdf/pdf-registry.generated.ts
// AUTO-GENERATED FROM CONTENT SCAN - DO NOT EDIT MANUALLY
// Generated: 2026-01-24T16:04:29.875Z

export const GENERATED_PDF_CONFIGS = [
  {
    "id": "abraham-vault-pack",
    "title": "Abraham Vault — Strategic Artifacts Pack",
    "description": "A disciplined vault of fillable PDFs and board-grade templates—built for leaders who decide, not drift.",
    "excerpt": "A disciplined vault of fillable PDFs and board-grade templates—built for leaders who decide, not drift.",
    "outputPath": "/assets/downloads/content-downloads/abraham-vault-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Vault",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.0 KB",
    "lastModified": "2026-01-24T16:04:29.412Z",
    "exists": true,
    "tags": [
      "Strategy",
      "Governance",
      "Decision-Making",
      "Leadership",
      "Frameworks"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "1ec1923e112c740960752d151863bec9"
  },
  {
    "id": "board-decision-log-template",
    "title": "Board Decision Log Template",
    "description": "Track decisions with context, trade-offs, owners, deadlines, evidence, and follow-through.",
    "excerpt": "A board-grade decision log for auditability, continuity, and accountability.",
    "outputPath": "/assets/downloads/content-downloads/board-decision-log-template.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "organizational",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.6 KB",
    "lastModified": "2026-01-24T16:04:29.432Z",
    "exists": true,
    "tags": [
      "board",
      "governance",
      "decisions",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "f25e077b170b08a1c29a62df66d4fba4"
  },
  {
    "id": "board-investor-onepager",
    "title": "Board & Investor One-Pager Template",
    "description": "A clean, professional one-pager template for board meetings and investor updates.",
    "excerpt": "Communicate clearly, concisely, and consistently with your board and investors.",
    "outputPath": "/assets/downloads/content-downloads/board-investor-onepager.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "organizational",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.5 KB",
    "lastModified": "2026-01-24T16:04:29.450Z",
    "exists": true,
    "tags": [
      "download",
      "template",
      "board",
      "investor",
      "strategy"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "0c126ee418457d215c05364aa7ad622e"
  },
  {
    "id": "brotherhood-covenant",
    "title": "Brotherhood Covenant",
    "description": "A simple covenant framework for men who choose to walk together in truth, loyalty and honour.",
    "excerpt": "A simple covenant framework for men who choose to walk together in truth, loyalty and honour.",
    "outputPath": "/assets/downloads/content-downloads/brotherhood-covenant.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Brotherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.9 KB",
    "lastModified": "2026-01-24T16:04:29.470Z",
    "exists": true,
    "tags": [
      "covenant",
      "brotherhood",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b12d38719845783e112d95340a87a6c0"
  },
  {
    "id": "canon-volume-iv-diagnostic-toolkit",
    "title": "Canon Volume IV - Culture-Decadence Diagnostic Toolkit",
    "description": "A professional-grade diagnostic toolkit designed to help leaders, reformers and institutional architects assess cultural strength, identify early signs of decadence and design renewal interventions.",
    "excerpt": "This toolkit includes the Canon's elite cultural diagnostic instruments: the Rise-Decay Index, Drift Spectrum, Cultural Softness Scale, Moral Imagination Audit and the Renewal Blueprint Generator.",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-iv-diagnostic-toolkit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-24T16:04:29.491Z",
    "exists": true,
    "tags": [
      "canon",
      "culture",
      "civilisation",
      "governance",
      "diagnostics",
      "renewal"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "654611c8df52d2b65bbf41628dbbb88b"
  },
  {
    "id": "canon-volume-v-governance-diagnostic-toolkit",
    "title": "Canon Volume V - Governance Diagnostic Toolkit",
    "description": "A comprehensive governance diagnostic system for assessing personal governance, organisational structures, institutional drift, and national stewardship.",
    "excerpt": "This professional-grade toolkit contains the Canon's governance instruments: the Authority Health Index, Governance Order Scale, Stewardship Competency Map, Institutional Drift Detector and the Long-Horizon Leadership Audit.",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-v-governance-diagnostic-toolkit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-24T16:04:29.510Z",
    "exists": true,
    "tags": [
      "canon",
      "governance",
      "leadership",
      "institutions",
      "diagnostics",
      "stewardship"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "bae2664d4d429f2e72facde627a0ff85"
  },
  {
    "id": "communication-script-bpf",
    "title": "Brotherhood Communication Script",
    "description": "A simple, repeatable script for honest, honouring conversations between brothers.",
    "excerpt": "A simple, repeatable script for honest, honouring conversations between brothers.",
    "outputPath": "/assets/downloads/content-downloads/communication-script-bpf.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Brotherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-24T16:04:29.528Z",
    "exists": true,
    "tags": [
      "brotherhood",
      "communication",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "5a1a95e1ed646f4559bf16c9bca3ebfa"
  },
  {
    "id": "decision-log-template",
    "title": "Decision Log Template",
    "description": "Decision Log Template - A resource from Abraham of London",
    "excerpt": "Decision Log Template - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/decision-log-template.pdf",
    "type": "tool",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "336.2 KB",
    "lastModified": "2025-12-28T16:40:32.355Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "cf5b65dd2ea18b93547a306c19b6be3b"
  },
  {
    "id": "decision-matrix-scorecard",
    "title": "Decision Matrix Scorecard",
    "description": "Use this when the room is split, the stakes are high, or emotions are masquerading as logic.",
    "excerpt": "A fillable weighted scoring tool for disciplined decision-making.",
    "outputPath": "/assets/downloads/content-downloads/decision-matrix-scorecard.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.7 KB",
    "lastModified": "2026-01-24T16:04:29.545Z",
    "exists": true,
    "tags": [
      "decision-making",
      "governance",
      "strategy",
      "scorecard"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "ccfd4c98804ff992a5e461bd431584a1"
  },
  {
    "id": "download-legacy-architecture-canvas",
    "title": "The Legacy Architecture Canvas",
    "description": "A fillable framework to crystallize your legacy thesis, map critical institutions, design governance guardrails, and establish the ritual of stewardship.",
    "excerpt": "The foundational instrument for designing a sovereign legacy. Move beyond sentiment to architect the durable transmission of values, capital, and culture.",
    "outputPath": "/assets/downloads/content-downloads/download-legacy-architecture-canvas.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "architect",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-24T16:04:29.564Z",
    "exists": true,
    "tags": [
      "legacy-architecture",
      "intergenerational-governance",
      "family-sovereignty",
      "strategic-formation",
      "heirloom-tools"
    ],
    "requiresAuth": true,
    "version": "1.0.0",
    "priority": 5,
    "preload": false,
    "md5": "64f8cfa0c3faa7b1c62bacd013b7b50a"
  },
  {
    "id": "entrepreneur-operating-pack",
    "title": "Entrepreneur Operating Pack",
    "description": "A comprehensive pack containing a 30-60-90 plan, a financial triage checklist, and key decision-making frameworks.",
    "excerpt": "A comprehensive pack containing a 30-60-90 plan, a financial triage checklist, and key decision-making frameworks.",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-operating-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Business",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-24T16:04:29.586Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "dc181d72a2df9ff3fb4ba70854791232"
  },
  {
    "id": "entrepreneur-survival-checklist",
    "title": "Entrepreneurial Survival Checklist",
    "description": "A practical, no-nonsense checklist to keep founders grounded, solvent and focused when the pressure rises.",
    "excerpt": "A practical, no-nonsense checklist to keep founders grounded, solvent and focused when the pressure rises.",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-survival-checklist.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Entrepreneurship",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-24T16:04:29.606Z",
    "exists": true,
    "tags": [
      "entrepreneurship",
      "survival",
      "strategy",
      "cashflow"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "14a936ef3f61e550e5a776bade432122"
  },
  {
    "id": "family-altar-liturgy",
    "title": "Family Altar Liturgy",
    "description": "A simple 15-20 minute framework for daily or weekly family worship that children can grow up remembering.",
    "excerpt": "A simple 15-20 minute framework for daily or weekly family worship that children can grow up remembering.",
    "outputPath": "/assets/downloads/content-downloads/family-altar-liturgy.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Family",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-24T16:04:29.624Z",
    "exists": true,
    "tags": [
      "family",
      "worship",
      "liturgy",
      "habits"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "8aee3330b7cfc500c465e6e51d904bae"
  },
  {
    "id": "leaders-cue-card-two-up",
    "title": "Leader's Cue Card (Two Up)",
    "description": "Weekly cadence, essential prompts, and crisis guardrails.",
    "excerpt": "Weekly cadence, essential prompts, and crisis guardrails.",
    "outputPath": "/assets/downloads/content-downloads/leaders-cue-card-two-up.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 KB",
    "lastModified": "2026-01-24T16:04:29.641Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "28706e40a8ccd40357223afab94f4a9e"
  },
  {
    "id": "leadership-playbook",
    "title": "The Leadership Playbook",
    "description": "A course curriculum to transform into a highly effective leader and catalyst for change.",
    "excerpt": "A course curriculum to transform into a highly effective leader and catalyst for change.",
    "outputPath": "/assets/downloads/content-downloads/leadership-playbook.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-24T16:04:29.658Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "9dd1f4c62c6e80db7cff61f60d4befb8"
  },
  {
    "id": "legacy-canvas",
    "title": "The Legacy Architecture Canvas",
    "description": "A disciplined, fillable framework to crystallize your legacy thesis, map critical institutions, design governance guardrails, and establish the ritual of stewardship.",
    "excerpt": "The foundational instrument for designing a sovereign legacy. Move beyond sentiment to architect the durable transmission of values, capital, and culture.",
    "outputPath": "/assets/downloads/content-downloads/legacy-canvas.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-24T16:04:29.675Z",
    "exists": true,
    "tags": [
      "legacy-architecture",
      "intergenerational-governance",
      "family-sovereignty",
      "strategic-formation",
      "heirloom-tools"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "6eb275b97863fa95418147e4afb65814"
  },
  {
    "id": "life-alignment-assessment",
    "title": "THE PRINCIPLES OF SURRENDER FRAMEWORK",
    "description": "Framework on surrender vs submission—voluntary alignment as the source of durable freedom, authority, and fulfilment.",
    "excerpt": "Framework on surrender vs submission—voluntary alignment as the source of durable freedom, authority, and fulfilment....",
    "outputPath": "/assets/downloads/content-downloads/life-alignment-assessment.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Frameworks",
    "tier": "public",
    "formats": [
      "A4"
    ],
    "fileSize": "92.0 KB",
    "lastModified": "2026-01-21T12:44:53.748Z",
    "exists": true,
    "tags": [
      "the-canon",
      "surrender",
      "alignment",
      "leadership",
      "institutional-formation",
      "civilisation"
    ],
    "requiresAuth": true,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "56089fbdc02852da298771db5428576d"
  },
  {
    "id": "mentorship-starter-kit",
    "title": "Mentorship Starter Kit",
    "description": "A practical starter kit for mentoring emerging leaders with clarity and structure.",
    "excerpt": "A practical starter kit for mentoring emerging leaders with clarity and structure.",
    "outputPath": "/assets/downloads/content-downloads/mentorship-starter-kit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.2 KB",
    "lastModified": "2026-01-24T16:04:29.692Z",
    "exists": true,
    "tags": [
      "leadership",
      "mentoring"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "4c5c454f5bf8970f6ee16940ca9145ed"
  },
  {
    "id": "operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "description": "Deploy an operating rhythm that makes execution predictable under constraint.",
    "excerpt": "A deck-based cadence system: weekly rhythm, governance checkpoints, scorecards, reviews.",
    "outputPath": "/assets/downloads/content-downloads/operating-cadence-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.6 KB",
    "lastModified": "2026-01-24T16:04:29.707Z",
    "exists": true,
    "tags": [
      "operations",
      "execution",
      "cadence",
      "governance"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "70d5aacdbaec9f8b6d0fb1bbbb041dce"
  },
  {
    "id": "principles-for-my-son-cue-card",
    "title": "Principles for My Son - Cue Card",
    "description": "Two-up A6: cut, carry, and read a line a day.",
    "excerpt": "Two-up A6: cut, carry, and read a line a day.",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son-cue-card.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Fatherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 KB",
    "lastModified": "2026-01-24T16:04:29.724Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "d76de0047847400f10d04772b29c6603"
  },
  {
    "id": "principles-for-my-son",
    "title": "Principles for My Son",
    "description": "Twelve principles for raising a boy who becomes a man of conviction in a confused age.",
    "excerpt": "Twelve principles for raising a boy who becomes a man of conviction in a confused age.",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-24T16:04:29.742Z",
    "exists": true,
    "tags": [
      "fatherhood",
      "legacy"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "f8fb5bda9cb894c5f4884ec9525869e1"
  },
  {
    "id": "purpose-pyramid-worksheet",
    "title": "Purpose Pyramid Worksheet",
    "description": "A fillable worksheet that turns vision into architecture: purpose → priorities → execution.",
    "excerpt": "Not a motivational prompt. A decision instrument.",
    "outputPath": "/assets/downloads/content-downloads/purpose-pyramid-worksheet.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Vault",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-24T16:04:29.757Z",
    "exists": true,
    "tags": [
      "purpose",
      "strategy",
      "execution",
      "vault"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "5fc76a54dd63c473b2b073125bb0bc67"
  },
  {
    "id": "scripture-track-john14",
    "title": "Scripture Track - John 14",
    "description": "Assurance • Obedience • The Helper • Peace",
    "excerpt": "Assurance • Obedience • The Helper • Peace",
    "outputPath": "/assets/downloads/content-downloads/scripture-track-john14.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Faith",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-24T16:04:29.774Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "067541cc1d3334fab7b827c71dd093e3"
  },
  {
    "id": "standards-brief",
    "title": "Standards Brief",
    "description": "Protect people, work, and name-especially under pressure.",
    "excerpt": "Protect people, work, and name-especially under pressure.",
    "outputPath": "/assets/downloads/content-downloads/standards-brief.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.8 KB",
    "lastModified": "2026-01-24T16:04:29.790Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "5fbaca22be745366d412246ddfc3876c"
  },
  {
    "id": "ultimate-purpose-of-man-editorial",
    "title": "Ultimate Purpose Of Man Editorial",
    "description": "Ultimate Purpose Of Man Editorial - A resource from Abraham of London",
    "excerpt": "Ultimate Purpose Of Man Editorial - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/ultimate-purpose-of-man-editorial.pdf",
    "type": "editorial",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 MB",
    "lastModified": "2026-01-02T17:18:50.915Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "cbbae65b374cf047590e73255d3912f4"
  },
  {
    "id": "weekly-operating-rhythm",
    "title": "Weekly Operating Rhythm & Daily Blocks",
    "description": "A template for high-leverage allocation of time and focus across the week.",
    "excerpt": "A template for high-leverage allocation of time and focus across the week.",
    "outputPath": "/assets/downloads/content-downloads/weekly-operating-rhythm.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Business",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.8 KB",
    "lastModified": "2026-01-24T16:04:29.806Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "8a880fc86e391a3a22f80133b7789c5f"
  },
  {
    "id": "decision-matrix-scorecard-fillable",
    "title": "Decision Matrix Scorecard Fillable",
    "description": "Decision Matrix Scorecard Fillable - A resource from Abraham of London",
    "excerpt": "Decision Matrix Scorecard Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/decision-matrix-scorecard-fillable.pdf",
    "type": "tool",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "35.8 KB",
    "lastModified": "2026-01-24T16:04:29.830Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "c1fc54c41c0f1b3e9fb6bad0c05b39a8"
  },
  {
    "id": "legacy-canvas-fillable",
    "title": "Legacy Canvas Fillable",
    "description": "Legacy Canvas Fillable - A resource from Abraham of London",
    "excerpt": "Legacy Canvas Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/legacy-canvas-fillable.pdf",
    "type": "canvas",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "10.5 KB",
    "lastModified": "2026-01-24T16:04:29.851Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b64bd18cce2ac1ba63fb7e4662025b30"
  },
  {
    "id": "purpose-pyramid-worksheet-fillable",
    "title": "Purpose Pyramid Worksheet Fillable",
    "description": "Purpose Pyramid Worksheet Fillable - A resource from Abraham of London",
    "excerpt": "Purpose Pyramid Worksheet Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/purpose-pyramid-worksheet-fillable.pdf",
    "type": "worksheet",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "19.8 KB",
    "lastModified": "2026-01-24T16:04:29.874Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b37f145c3c79e6c6b8ba39385620cfb3"
  }
] as const;
export const GENERATED_AT = "2026-01-24T16:04:29.875Z";
export const GENERATED_COUNT = 29;
