// scripts/pdf/pdf-registry.source.ts
// Canonical source-of-truth registry for ALL PDFs (legacy + new).
// This file is consumed by build-pdf-registry-generated.ts ONLY.
//
// NOTE:
// - This registry is NOT “folder-aware”. If a PDF is on disk but not listed here,
//   it will be invisible to your Next-safe registry.
// - Output paths below match what you actually have under /public/assets/downloads/** right now,
//   so your dashboard can “see” the library immediately.

type Tier = "free" | "member" | "architect" | "inner-circle" | "inner-circle-elite";

export type SourcePDFItem = {
  id: string;
  title: string;
  type: string;
  tier: Tier;

  // canonical URL path (must exist under /public)
  outputPath: string;

  description?: string;
  excerpt?: string;
  tags?: string[];

  // paper variants you WANT this asset to support
  // - ["bundle"] = single non-variant file
  // - ["A4"] = single paper size, no variants needed
  // - ["A4","Letter","A3"] = true multi-variant, builder creates __a4/__letter/__a3
  formats?: Array<"A4" | "Letter" | "A3" | "bundle">;

  // file-format (usually PDF)
  format?: "PDF" | "EXCEL" | "POWERPOINT" | "ZIP" | "BINARY";

  isInteractive?: boolean;
  isFillable?: boolean;
  requiresAuth?: boolean;

  version?: string;
  author?: string;
  category?: string;

  createdAt?: string;
  updatedAt?: string;

  priority?: number;
  preload?: boolean;
};

// -----------------------------------------------------------------------------
// NEW / GENERATED (may be missing on disk until you generate them)
// -----------------------------------------------------------------------------

const NEW_PDFS: SourcePDFItem[] = [
  {
    id: "personal-alignment-assessment-fillable",
    title: "Personal Alignment Assessment (Fillable)",
    type: "assessment",
    tier: "free",
    outputPath: "/assets/downloads/personal-alignment-assessment-fillable.pdf",
    description:
      "Interactive fillable assessment to audit agency, purpose, integrity, and alignment with principle-led living.",
    excerpt: "Fillable interactive assessment • Agency • Purpose • Integrity",
    tags: ["assessment", "alignment", "fillable", "personal-growth"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
    priority: 10,
    preload: false,
  },

  // IMPORTANT:
  // You currently have:
  // - /assets/downloads/life-alignment-assessment-a4.pdf
  // - /assets/downloads/life-alignment-assessment-letter.pdf
  // - /assets/downloads/life-alignment-assessment-a3.pdf
  // - /assets/downloads/content-downloads/life-alignment-assessment.pdf
  //
  // But you do NOT have /assets/downloads/life-alignment-assessment.pdf (base) on disk.
  // So we register the BASE against the *existing* file in content-downloads,
  // and register the 3 root variants as separate “static” PDFs below in LEGACY_PDFS.
  {
    id: "life-alignment-assessment",
    title: "Life Alignment Assessment",
    type: "assessment",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/life-alignment-assessment.pdf",
    description: "Assessment worksheet used to evaluate alignment across core domains of life.",
    excerpt: "A structured self-audit for direction, discipline, and conviction.",
    tags: ["alignment", "assessment", "worksheet"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
    priority: 1,
    preload: true,
  },

  // The two you explicitly called out.
  {
    id: "surrender-framework",
    title: "The Principles of Surrender Framework",
    type: "framework",
    tier: "free",
    outputPath: "/assets/downloads/surrender-framework.pdf",
    description: "The core framework document outlining the Principles of Surrender.",
    excerpt: "A structured model for spiritual and strategic alignment.",
    tags: ["surrender", "framework", "alignment", "principles"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "surrender-framework",
    priority: 2,
    preload: true,
  },
  {
    id: "surrender-principles",
    title: "Principles of Surrender (Worksheet)",
    type: "worksheet",
    tier: "free",
    outputPath: "/assets/downloads/surrender-principles.pdf",
    description: "A worksheet to apply the Principles of Surrender framework in daily life.",
    excerpt: "Simple prompts and structure to operationalise surrender as discipline.",
    tags: ["surrender", "worksheet", "discipline"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "surrender-framework",
    priority: 3,
    preload: false,
  },
];

// -----------------------------------------------------------------------------
// LEGACY LIBRARY (these are already on disk under /public/assets/downloads/**)
// -----------------------------------------------------------------------------

const LEGACY_PDFS: SourcePDFItem[] = [
  // ---------------------------------------------------------------------------
  // Root-level PDFs in /public/assets/downloads
  // ---------------------------------------------------------------------------

  {
    id: "legacy-architecture-canvas-a4-premium-architect",
    title: "Legacy Architecture Canvas (A4 • Premium Architect)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a4-premium-architect.pdf",
    description: "Legacy Architecture Canvas — premium architect export (A4).",
    tags: ["legacy", "canvas", "architect", "a4"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: false,
  },
  {
    id: "legacy-architecture-canvas-letter-premium-architect",
    title: "Legacy Architecture Canvas (Letter • Premium Architect)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/legacy-architecture-canvas-letter-premium-architect.pdf",
    description: "Legacy Architecture Canvas — premium architect export (Letter).",
    tags: ["legacy", "canvas", "architect", "letter"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: false,
  },
  {
    id: "legacy-architecture-canvas-a3-premium-architect",
    title: "Legacy Architecture Canvas (A3 • Premium Architect)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a3-premium-architect.pdf",
    description: "Legacy Architecture Canvas — premium architect export (A3).",
    tags: ["legacy", "canvas", "architect", "a3"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: false,
  },

  // ---------------------------------------------------------------------------
  // ✅ NEW: unlisted PDFs reported by audit
  // ---------------------------------------------------------------------------

  {
    id: "legacy-architecture-canvas-a4-premium-architect-interactive",
    title: "Legacy Architecture Canvas (A4 • Premium Architect • Interactive)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a4-premium-architect-interactive.pdf",
    description: "Legacy Architecture Canvas — premium architect export (A4), interactive/fillable variant.",
    tags: ["legacy", "canvas", "architect", "a4", "interactive", "fillable"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: false,
  },
  {
    id: "legacy-architecture-canvas-letter-premium-architect-interactive",
    title: "Legacy Architecture Canvas (Letter • Premium Architect • Interactive)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/legacy-architecture-canvas-letter-premium-architect-interactive.pdf",
    description: "Legacy Architecture Canvas — premium architect export (Letter), interactive/fillable variant.",
    tags: ["legacy", "canvas", "architect", "letter", "interactive", "fillable"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: false,
  },
  {
    id: "ultimate-purpose-of-man-editorial-a4-premium-architect",
    title: "Ultimate Purpose of Man (Editorial • A4 • Premium Architect)",
    type: "editorial",
    tier: "free",
    outputPath: "/assets/downloads/ultimate-purpose-of-man-editorial-a4-premium-architect.pdf",
    description: "Ultimate Purpose of Man — editorial export (A4), premium architect build.",
    tags: ["purpose", "editorial", "theology", "a4", "premium", "architect"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: false,
    version: "1.0.0",
    category: "theology",
    preload: false,
  },

  // Your 3 generated root variants (present on disk)
  {
    id: "life-alignment-assessment-a4",
    title: "Life Alignment Assessment (A4)",
    type: "assessment",
    tier: "free",
    outputPath: "/assets/downloads/life-alignment-assessment-a4.pdf",
    description: "Life Alignment Assessment — A4 variant.",
    tags: ["alignment", "assessment", "a4"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
    preload: true,
  },
  {
    id: "life-alignment-assessment-letter",
    title: "Life Alignment Assessment (Letter)",
    type: "assessment",
    tier: "free",
    outputPath: "/assets/downloads/life-alignment-assessment-letter.pdf",
    description: "Life Alignment Assessment — Letter variant.",
    tags: ["alignment", "assessment", "letter"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
    preload: true,
  },
  {
    id: "life-alignment-assessment-a3",
    title: "Life Alignment Assessment (A3)",
    type: "assessment",
    tier: "free",
    outputPath: "/assets/downloads/life-alignment-assessment-a3.pdf",
    description: "Life Alignment Assessment — A3 variant.",
    tags: ["alignment", "assessment", "a3"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
    preload: true,
  },

  // ---------------------------------------------------------------------------
  // content-downloads (main legacy library)
  // ---------------------------------------------------------------------------

  {
    id: "abraham-vault-pack",
    title: "Abraham Vault Pack",
    type: "bundle",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/abraham-vault-pack.pdf",
    description: "Compiled vault pack of strategic tools and templates.",
    tags: ["vault", "bundle", "pack"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
    preload: false,
  },
  {
    id: "board-decision-log-template",
    title: "Board Decision Log Template",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/board-decision-log-template.pdf",
    description: "Board-grade decision log template.",
    tags: ["board", "decision", "log", "template"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "governance",
  },
  {
    id: "board-investor-onepager",
    title: "Board Investor One-Pager",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/board-investor-onepager.pdf",
    description: "Investor-ready one-pager format (board standard).",
    tags: ["board", "investor", "onepager"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "governance",
  },
  {
    id: "brotherhood-covenant",
    title: "Brotherhood Covenant",
    type: "framework",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/brotherhood-covenant.pdf",
    description: "A covenant framework for brotherhood and accountable fellowship.",
    tags: ["brotherhood", "covenant", "discipline"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "canon-volume-iv-diagnostic-toolkit",
    title: "Canon Volume IV Diagnostic Toolkit",
    type: "toolkit",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/canon-volume-iv-diagnostic-toolkit.pdf",
    description: "Diagnostic toolkit aligned to Canon Volume IV.",
    tags: ["canon", "toolkit", "diagnostic"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "canon",
  },
  {
    id: "canon-volume-v-governance-diagnostic-toolkit",
    title: "Canon Volume V Governance Diagnostic Toolkit",
    type: "toolkit",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/canon-volume-v-governance-diagnostic-toolkit.pdf",
    description: "Governance diagnostic toolkit aligned to Canon Volume V.",
    tags: ["canon", "governance", "toolkit", "diagnostic"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "governance",
  },
  {
    id: "communication-script-bpf",
    title: "Communication Script (BPF)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/communication-script-bpf.pdf",
    description: "Communication script template (BPF).",
    tags: ["communication", "script"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "decision-log-template-content",
    title: "Decision Log Template",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/decision-log-template.pdf",
    description: "Decision log template for disciplined execution.",
    tags: ["decision", "log", "template"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "decision-matrix-scorecard-content",
    title: "Decision Matrix Scorecard",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/decision-matrix-scorecard.pdf",
    description: "Weighted decision matrix scorecard.",
    tags: ["decision", "matrix", "scorecard"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "download-legacy-architecture-canvas",
    title: "Download: Legacy Architecture Canvas",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/download-legacy-architecture-canvas.pdf",
    description: "Download page export for Legacy Architecture Canvas.",
    tags: ["legacy", "canvas", "download"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
  },
  {
    id: "entrepreneur-operating-pack",
    title: "Entrepreneur Operating Pack",
    type: "pack",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/entrepreneur-operating-pack.pdf",
    description: "Operating pack for founders: cadence, decisions, and execution scaffolding.",
    tags: ["entrepreneur", "operating", "pack"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "entrepreneur-survival-checklist",
    title: "Entrepreneur Survival Checklist",
    type: "checklist",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/entrepreneur-survival-checklist.pdf",
    description: "Survival checklist for founder resilience and execution discipline.",
    tags: ["entrepreneur", "checklist", "resilience"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "family-altar-liturgy",
    title: "Family Altar Liturgy",
    type: "liturgy",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/family-altar-liturgy.pdf",
    description: "Structured liturgy for family altar and household worship.",
    tags: ["family", "altar", "liturgy", "faith"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "theology",
  },
  {
    id: "leaders-cue-card-two-up",
    title: "Leaders Cue Card (Two-Up)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/leaders-cue-card-two-up.pdf",
    description: "Leader cue card layout (two-up printing).",
    tags: ["leaders", "cue-card", "leadership"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "leadership-playbook",
    title: "Leadership Playbook",
    type: "playbook",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/leadership-playbook.pdf",
    description: "Leadership playbook: principles, tactics, and operating doctrine.",
    tags: ["leadership", "playbook"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "legacy-architecture-canvas-content",
    title: "Legacy Architecture Canvas",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/legacy-architecture-canvas.pdf",
    description: "Legacy Architecture Canvas (standard library export).",
    tags: ["legacy", "canvas"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
    preload: true,
  },
  {
    id: "legacy-canvas",
    title: "Legacy Canvas",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/legacy-canvas.pdf",
    description: "Legacy Canvas worksheet for personal and generational design.",
    tags: ["legacy", "canvas", "worksheet"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
  },
  {
    id: "mentorship-starter-kit",
    title: "Mentorship Starter Kit",
    type: "toolkit",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/mentorship-starter-kit.pdf",
    description: "Starter kit to structure mentorship, expectations, and progress.",
    tags: ["mentorship", "toolkit", "leadership"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "operating-cadence-pack",
    title: "Operating Cadence Pack",
    type: "pack",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/operating-cadence-pack.pdf",
    description: "Operating cadence pack for execution, rhythm, and accountability.",
    tags: ["operating", "cadence", "pack", "operations"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "principles-for-my-son-cue-card",
    title: "Principles for My Son (Cue Card)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/principles-for-my-son-cue-card.pdf",
    description: "Cue card version of 'Principles for My Son'.",
    tags: ["principles", "fatherhood", "cue-card"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "family",
  },
  {
    id: "principles-for-my-son",
    title: "Principles for My Son",
    type: "editorial",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/principles-for-my-son.pdf",
    description: "A principles document addressed to your son: doctrine, discipline, destiny.",
    tags: ["principles", "fatherhood", "family"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "family",
  },
  {
    id: "purpose-pyramid-worksheet",
    title: "Purpose Pyramid Worksheet",
    type: "worksheet",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/purpose-pyramid-worksheet.pdf",
    description: "Worksheet to structure purpose across levels of calling and execution.",
    tags: ["purpose", "worksheet", "framework"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
  },
  {
    id: "scripture-track-john14",
    title: "Scripture Track: John 14",
    type: "study",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/scripture-track-john14.pdf",
    description: "Structured scripture track and reflection guide (John 14).",
    tags: ["scripture", "john14", "study", "faith"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "theology",
  },
  {
    id: "standards-brief",
    title: "Standards Brief",
    type: "brief",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/standards-brief.pdf",
    description: "Standards brief: expectations, boundaries, and operating rules.",
    tags: ["standards", "brief", "leadership"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "leadership",
  },
  {
    id: "ultimate-purpose-of-man-editorial",
    title: "Ultimate Purpose of Man (Editorial)",
    type: "editorial",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/ultimate-purpose-of-man-editorial.pdf",
    description: "Editorial: ultimate purpose, meaning, and moral destiny.",
    tags: ["purpose", "editorial", "theology"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "theology",
    preload: false,
  },
  {
    id: "weekly-operating-rhythm",
    title: "Weekly Operating Rhythm",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/content-downloads/weekly-operating-rhythm.pdf",
    description: "Weekly operating rhythm template for cadence and throughput.",
    tags: ["weekly", "operating", "rhythm", "operations"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },

  // ---------------------------------------------------------------------------
  // lib-pdf (library duplicates / fillable assets)
  // ---------------------------------------------------------------------------

  {
    id: "decision-log-template-lib",
    title: "Decision Log Template (Library)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/lib-pdf/decision-log-template.pdf",
    description: "Library copy of the decision log template.",
    tags: ["decision", "log", "template", "library"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "decision-matrix-scorecard-fillable-lib",
    title: "Decision Matrix Scorecard (Fillable • Library)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/lib-pdf/decision-matrix-scorecard-fillable.pdf",
    description: "Fillable library version of the decision matrix scorecard.",
    tags: ["decision", "matrix", "scorecard", "fillable", "library"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "operations",
  },
  {
    id: "legacy-canvas-fillable-lib",
    title: "Legacy Canvas (Fillable • Library)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/lib-pdf/legacy-canvas-fillable.pdf",
    description: "Fillable library version of the legacy canvas.",
    tags: ["legacy", "canvas", "fillable", "library"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "legacy",
  },
  {
    id: "purpose-pyramid-worksheet-fillable-lib",
    title: "Purpose Pyramid Worksheet (Fillable • Library)",
    type: "worksheet",
    tier: "free",
    outputPath: "/assets/downloads/lib-pdf/purpose-pyramid-worksheet-fillable.pdf",
    description: "Fillable library version of the purpose pyramid worksheet.",
    tags: ["purpose", "worksheet", "fillable", "library"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "personal-growth",
  },
  {
    id: "ultimate-purpose-of-man-editorial-lib",
    title: "Ultimate Purpose of Man (Editorial • Library)",
    type: "editorial",
    tier: "free",
    outputPath: "/assets/downloads/lib-pdf/ultimate-purpose-of-man-editorial.pdf",
    description: "Library copy of the Ultimate Purpose editorial.",
    tags: ["purpose", "editorial", "library"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "theology",
  },

  // ---------------------------------------------------------------------------
  // public-assets/resources/pdfs
  // ---------------------------------------------------------------------------

  {
    id: "brotherhood-starter-kit-resource",
    title: "Brotherhood Starter Kit",
    type: "toolkit",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/resources/pdfs/brotherhood-starter-kit.pdf",
    description: "Resource pack: brotherhood starter kit.",
    tags: ["brotherhood", "starter-kit", "resource"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "resources",
  },
  {
    id: "destiny-mapping-worksheet-resource",
    title: "Destiny Mapping Worksheet",
    type: "worksheet",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/resources/pdfs/destiny-mapping-worksheet.pdf",
    description: "Worksheet to map destiny themes into strategy and execution.",
    tags: ["destiny", "mapping", "worksheet", "resource"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "resources",
  },
  {
    id: "fatherhood-impact-framework-resource",
    title: "Fatherhood Impact Framework",
    type: "framework",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/resources/pdfs/fatherhood-impact-framework.pdf",
    description: "Framework for fatherhood impact: presence, formation, legacy.",
    tags: ["fatherhood", "framework", "resource"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "resources",
  },
  {
    id: "institutional-health-scorecard-resource",
    title: "Institutional Health Scorecard",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/resources/pdfs/institutional-health-scorecard.pdf",
    description: "Scorecard for assessing institutional health and resilience.",
    tags: ["institutional", "health", "scorecard", "resource"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "resources",
  },
  {
    id: "leadership-standards-blueprint-resource",
    title: "Leadership Standards Blueprint",
    type: "blueprint",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/resources/pdfs/leadership-standards-blueprint.pdf",
    description: "Blueprint defining leadership standards, boundaries, and expectations.",
    tags: ["leadership", "standards", "blueprint", "resource"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "resources",
  },

  // ---------------------------------------------------------------------------
  // public-assets/vault (vault duplicates)
  // ---------------------------------------------------------------------------

  {
    id: "board-decision-log-template-vault",
    title: "Board Decision Log Template (Vault)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/board-decision-log-template.pdf",
    description: "Vault copy of the board decision log template.",
    tags: ["board", "decision", "log", "vault"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },
  {
    id: "decision-log-template-vault",
    title: "Decision Log Template (Vault)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/decision-log-template.pdf",
    description: "Vault copy of the decision log template.",
    tags: ["decision", "log", "vault"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },
  {
    id: "decision-matrix-scorecard-fillable-vault",
    title: "Decision Matrix Scorecard (Fillable • Vault)",
    type: "tool",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/decision-matrix-scorecard-fillable.pdf",
    description: "Vault copy of the fillable decision matrix scorecard.",
    tags: ["decision", "matrix", "scorecard", "fillable", "vault"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },
  {
    id: "legacy-canvas-fillable-vault",
    title: "Legacy Canvas (Fillable • Vault)",
    type: "canvas",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/legacy-canvas-fillable.pdf",
    description: "Vault copy of the fillable legacy canvas.",
    tags: ["legacy", "canvas", "fillable", "vault"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },
  {
    id: "operating-cadence-pack-vault",
    title: "Operating Cadence Pack (Vault)",
    type: "pack",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/operating-cadence-pack.pdf",
    description: "Vault copy of the operating cadence pack.",
    tags: ["operating", "cadence", "pack", "vault"],
    formats: ["bundle"],
    format: "PDF",
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },
  {
    id: "purpose-pyramid-worksheet-fillable-vault",
    title: "Purpose Pyramid Worksheet (Fillable • Vault)",
    type: "worksheet",
    tier: "free",
    outputPath: "/assets/downloads/public-assets/vault/purpose-pyramid-worksheet-fillable.pdf",
    description: "Vault copy of the fillable purpose pyramid worksheet.",
    tags: ["purpose", "worksheet", "fillable", "vault"],
    formats: ["bundle"],
    format: "PDF",
    isFillable: true,
    requiresAuth: false,
    version: "1.0.0",
    category: "vault",
  },

  // ---------------------------------------------------------------------------
  // enterprise architect canvas variants (on disk, previously unlisted)
  // ---------------------------------------------------------------------------

  {
    id: "legacy-architecture-canvas-a3-enterprise-architect",
    title: "Legacy Architecture Canvas (A3, Enterprise, Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a3-enterprise-architect.pdf",
    description: "Legacy Architecture Canvas — A3, enterprise quality, architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "a3"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
    priority: 5,
  },
  {
    id: "legacy-architecture-canvas-a4-enterprise-architect",
    title: "Legacy Architecture Canvas (A4, Enterprise, Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a4-enterprise-architect.pdf",
    description: "Legacy Architecture Canvas — A4, enterprise quality, architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "a4"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
    priority: 5,
  },
  {
    id: "legacy-architecture-canvas-letter-enterprise-architect",
    title: "Legacy Architecture Canvas (Letter, Enterprise, Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-letter-enterprise-architect.pdf",
    description: "Legacy Architecture Canvas — Letter, enterprise quality, architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "letter"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: true,
    isFillable: true,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
    priority: 5,
  },
];

// ... continuing from previous block
  {
    id: "legacy-architecture-canvas-a3-enterprise-architect",
    title: "Legacy Architecture Canvas (A3 • Enterprise Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a3-enterprise-architect.pdf",
    description: "Enterprise-grade Legacy Architecture Canvas (A3) for Architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "a3"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
  },
  {
    id: "legacy-architecture-canvas-a4-enterprise-architect",
    title: "Legacy Architecture Canvas (A4 • Enterprise Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-a4-enterprise-architect.pdf",
    description: "Enterprise-grade Legacy Architecture Canvas (A4) for Architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "a4"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
  },
  {
    id: "legacy-architecture-canvas-letter-enterprise-architect",
    title: "Legacy Architecture Canvas (Letter • Enterprise Architect)",
    type: "canvas",
    tier: "architect",
    outputPath: "/assets/downloads/legacy-architecture-canvas-letter-enterprise-architect.pdf",
    description: "Enterprise-grade Legacy Architecture Canvas (Letter) for Architect tier.",
    tags: ["legacy", "canvas", "enterprise", "architect", "letter"],
    formats: ["bundle"],
    format: "PDF",
    isInteractive: false,
    isFillable: false,
    requiresAuth: true,
    version: "1.0.0",
    category: "legacy",
  },
];

// -----------------------------------------------------------------------------
// FINAL REGISTRY ASSEMBLY
// -----------------------------------------------------------------------------

/**
 * Combined Source of Truth.
 * This is the variable imported by the generator script.
 */
export const ALL_SOURCE_PDFS: SourcePDFItem[] = [
  ...NEW_PDFS,
  ...LEGACY_PDFS,
];

/**
 * Utility to find a PDF by ID (used for API and Build Lookups)
 */
export function getSourcePDFById(id: string): SourcePDFItem | undefined {
  return ALL_SOURCE_PDFS.find((p) => p.id === id);
}

// -----------------------------------------------------------------------------
// EXPORT
// -----------------------------------------------------------------------------

export function getPDFRegistrySource(): SourcePDFItem[] {
  // Deterministic order: legacy first, then new
  return [...LEGACY_PDFS, ...NEW_PDFS];
}