// scripts/pdf/pdf-registry.generated.ts
// AUTO-GENERATED FROM CONTENT SCAN - DO NOT EDIT MANUALLY
// Generated: 2026-01-23T12:06:24.031Z

export const GENERATED_PDF_CONFIGS = [
  {
    "id": "abraham-vault-pack",
    "title": "Abraham Vault — Strategic Artifacts Pack",
    "description": "A disciplined vault of fillable PDFs and board-grade templates—built for leaders who decide, not drift.",
    "excerpt": "A disciplined vault of fillable PDFs and board-grade templates—built for leaders who decide, not drift.",
    "outputPath": "/assets/downloads/content-downloads/abraham-vault-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Vault",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.0 KB",
    "lastModified": "2026-01-23T12:06:23.461Z",
    "exists": true,
    "tags": [
      "Strategy",
      "Governance",
      "Decision-Making",
      "Leadership",
      "Frameworks"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "961765dfb9ad57d4aba7a492d806eb99"
  },
  {
    "id": "board-decision-log-template",
    "title": "Board Decision Log Template",
    "description": "Track decisions with context, trade-offs, owners, deadlines, evidence, and follow-through.",
    "excerpt": "A board-grade decision log for auditability, continuity, and accountability.",
    "outputPath": "/assets/downloads/content-downloads/board-decision-log-template.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "organizational",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.6 KB",
    "lastModified": "2026-01-23T12:06:23.491Z",
    "exists": true,
    "tags": [
      "board",
      "governance",
      "decisions",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "03200aae4b8818b7d6f73f402331d5ce"
  },
  {
    "id": "board-investor-onepager",
    "title": "Board & Investor One-Pager Template",
    "description": "A clean, professional one-pager template for board meetings and investor updates.",
    "excerpt": "Communicate clearly, concisely, and consistently with your board and investors.",
    "outputPath": "/assets/downloads/content-downloads/board-investor-onepager.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "organizational",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.5 KB",
    "lastModified": "2026-01-23T12:06:23.512Z",
    "exists": true,
    "tags": [
      "download",
      "template",
      "board",
      "investor",
      "strategy"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "ad1c84701a1f717e7976140c34bd6c9b"
  },
  {
    "id": "brotherhood-covenant",
    "title": "Brotherhood Covenant",
    "description": "A simple covenant framework for men who choose to walk together in truth, loyalty and honour.",
    "excerpt": "A simple covenant framework for men who choose to walk together in truth, loyalty and honour.",
    "outputPath": "/assets/downloads/content-downloads/brotherhood-covenant.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Brotherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.9 KB",
    "lastModified": "2026-01-23T12:06:23.536Z",
    "exists": true,
    "tags": [
      "covenant",
      "brotherhood",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "7ba633099e3ab250e3a1fa2078d484a6"
  },
  {
    "id": "canon-volume-iv-diagnostic-toolkit",
    "title": "Canon Volume IV - Culture-Decadence Diagnostic Toolkit",
    "description": "A professional-grade diagnostic toolkit designed to help leaders, reformers and institutional architects assess cultural strength, identify early signs of decadence and design renewal interventions.",
    "excerpt": "This toolkit includes the Canon's elite cultural diagnostic instruments: the Rise-Decay Index, Drift Spectrum, Cultural Softness Scale, Moral Imagination Audit and the Renewal Blueprint Generator.",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-iv-diagnostic-toolkit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-23T12:06:23.566Z",
    "exists": true,
    "tags": [
      "canon",
      "culture",
      "civilisation",
      "governance",
      "diagnostics",
      "renewal"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b97c2124a63681b38bc14fcf2017b7e3"
  },
  {
    "id": "canon-volume-v-governance-diagnostic-toolkit",
    "title": "Canon Volume V - Governance Diagnostic Toolkit",
    "description": "A comprehensive governance diagnostic system for assessing personal governance, organisational structures, institutional drift, and national stewardship.",
    "excerpt": "This professional-grade toolkit contains the Canon's governance instruments: the Authority Health Index, Governance Order Scale, Stewardship Competency Map, Institutional Drift Detector and the Long-Horizon Leadership Audit.",
    "outputPath": "/assets/downloads/content-downloads/canon-volume-v-governance-diagnostic-toolkit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-23T12:06:23.593Z",
    "exists": true,
    "tags": [
      "canon",
      "governance",
      "leadership",
      "institutions",
      "diagnostics",
      "stewardship"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "9229718cc79b5f7ae12711d80b4493ee"
  },
  {
    "id": "communication-script-bpf",
    "title": "Brotherhood Communication Script",
    "description": "A simple, repeatable script for honest, honouring conversations between brothers.",
    "excerpt": "A simple, repeatable script for honest, honouring conversations between brothers.",
    "outputPath": "/assets/downloads/content-downloads/communication-script-bpf.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Brotherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-23T12:06:23.616Z",
    "exists": true,
    "tags": [
      "brotherhood",
      "communication",
      "accountability"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "84fba74fb32360d1f83fe4ac0eb80ebb"
  },
  {
    "id": "decision-log-template",
    "title": "Decision Log Template",
    "description": "Decision Log Template - A resource from Abraham of London",
    "excerpt": "Decision Log Template - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/decision-log-template.pdf",
    "type": "tool",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "336.2 KB",
    "lastModified": "2025-12-28T16:40:32.355Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "cf5b65dd2ea18b93547a306c19b6be3b"
  },
  {
    "id": "decision-matrix-scorecard",
    "title": "Decision Matrix Scorecard",
    "description": "Use this when the room is split, the stakes are high, or emotions are masquerading as logic.",
    "excerpt": "A fillable weighted scoring tool for disciplined decision-making.",
    "outputPath": "/assets/downloads/content-downloads/decision-matrix-scorecard.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.7 KB",
    "lastModified": "2026-01-23T12:06:23.642Z",
    "exists": true,
    "tags": [
      "decision-making",
      "governance",
      "strategy",
      "scorecard"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "10e1ed44383da24169c77feecb354bca"
  },
  {
    "id": "download-legacy-architecture-canvas",
    "title": "The Legacy Architecture Canvas",
    "description": "A fillable framework to crystallize your legacy thesis, map critical institutions, design governance guardrails, and establish the ritual of stewardship.",
    "excerpt": "The foundational instrument for designing a sovereign legacy. Move beyond sentiment to architect the durable transmission of values, capital, and culture.",
    "outputPath": "/assets/downloads/content-downloads/download-legacy-architecture-canvas.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "architect",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-23T12:06:23.666Z",
    "exists": true,
    "tags": [
      "legacy-architecture",
      "intergenerational-governance",
      "family-sovereignty",
      "strategic-formation",
      "heirloom-tools"
    ],
    "requiresAuth": true,
    "version": "1.0.0",
    "priority": 5,
    "preload": false,
    "md5": "8fa3d974ddaaffb4036959a05db2a046"
  },
  {
    "id": "entrepreneur-operating-pack",
    "title": "Entrepreneur Operating Pack",
    "description": "A comprehensive pack containing a 30-60-90 plan, a financial triage checklist, and key decision-making frameworks.",
    "excerpt": "A comprehensive pack containing a 30-60-90 plan, a financial triage checklist, and key decision-making frameworks.",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-operating-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Business",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-23T12:06:23.693Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "c8a4221906a638b303cb048b4b14118a"
  },
  {
    "id": "entrepreneur-survival-checklist",
    "title": "Entrepreneurial Survival Checklist",
    "description": "A practical, no-nonsense checklist to keep founders grounded, solvent and focused when the pressure rises.",
    "excerpt": "A practical, no-nonsense checklist to keep founders grounded, solvent and focused when the pressure rises.",
    "outputPath": "/assets/downloads/content-downloads/entrepreneur-survival-checklist.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Entrepreneurship",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-23T12:06:23.717Z",
    "exists": true,
    "tags": [
      "entrepreneurship",
      "survival",
      "strategy",
      "cashflow"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "561eb98911d2a0a1582f861987432dc5"
  },
  {
    "id": "family-altar-liturgy",
    "title": "Family Altar Liturgy",
    "description": "A simple 15-20 minute framework for daily or weekly family worship that children can grow up remembering.",
    "excerpt": "A simple 15-20 minute framework for daily or weekly family worship that children can grow up remembering.",
    "outputPath": "/assets/downloads/content-downloads/family-altar-liturgy.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Family",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-23T12:06:23.736Z",
    "exists": true,
    "tags": [
      "family",
      "worship",
      "liturgy",
      "habits"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "df05bfcb2cc16da7503bc74c8b250265"
  },
  {
    "id": "leaders-cue-card-two-up",
    "title": "Leader's Cue Card (Two Up)",
    "description": "Weekly cadence, essential prompts, and crisis guardrails.",
    "excerpt": "Weekly cadence, essential prompts, and crisis guardrails.",
    "outputPath": "/assets/downloads/content-downloads/leaders-cue-card-two-up.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 KB",
    "lastModified": "2026-01-23T12:06:23.757Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "4386b074ed77a3414f41928c433491e2"
  },
  {
    "id": "leadership-playbook",
    "title": "The Leadership Playbook",
    "description": "A course curriculum to transform into a highly effective leader and catalyst for change.",
    "excerpt": "A course curriculum to transform into a highly effective leader and catalyst for change.",
    "outputPath": "/assets/downloads/content-downloads/leadership-playbook.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-23T12:06:23.779Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "ed4b413dcb736a99d724e2680efed2d2"
  },
  {
    "id": "legacy-canvas",
    "title": "The Legacy Architecture Canvas",
    "description": "A disciplined, fillable framework to crystallize your legacy thesis, map critical institutions, design governance guardrails, and establish the ritual of stewardship.",
    "excerpt": "The foundational instrument for designing a sovereign legacy. Move beyond sentiment to architect the durable transmission of values, capital, and culture.",
    "outputPath": "/assets/downloads/content-downloads/legacy-canvas.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.1 KB",
    "lastModified": "2026-01-23T12:06:23.799Z",
    "exists": true,
    "tags": [
      "legacy-architecture",
      "intergenerational-governance",
      "family-sovereignty",
      "strategic-formation",
      "heirloom-tools"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "6cd8fbf40798288a8989adf282e343f8"
  },
  {
    "id": "life-alignment-assessment",
    "title": "THE PRINCIPLES OF SURRENDER FRAMEWORK",
    "description": "Framework on surrender vs submission—voluntary alignment as the source of durable freedom, authority, and fulfilment.",
    "excerpt": "Framework on surrender vs submission—voluntary alignment as the source of durable freedom, authority, and fulfilment....",
    "outputPath": "/assets/downloads/content-downloads/life-alignment-assessment.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Frameworks",
    "tier": "public",
    "formats": [
      "A4"
    ],
    "fileSize": "92.0 KB",
    "lastModified": "2026-01-21T12:44:53.748Z",
    "exists": true,
    "tags": [
      "the-canon",
      "surrender",
      "alignment",
      "leadership",
      "institutional-formation",
      "civilisation"
    ],
    "requiresAuth": true,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "56089fbdc02852da298771db5428576d"
  },
  {
    "id": "mentorship-starter-kit",
    "title": "Mentorship Starter Kit",
    "description": "A practical starter kit for mentoring emerging leaders with clarity and structure.",
    "excerpt": "A practical starter kit for mentoring emerging leaders with clarity and structure.",
    "outputPath": "/assets/downloads/content-downloads/mentorship-starter-kit.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.2 KB",
    "lastModified": "2026-01-23T12:06:23.818Z",
    "exists": true,
    "tags": [
      "leadership",
      "mentoring"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "c5b4ff7c49894180b877502163df95bc"
  },
  {
    "id": "operating-cadence-pack",
    "title": "Operating Cadence Pack",
    "description": "Deploy an operating rhythm that makes execution predictable under constraint.",
    "excerpt": "A deck-based cadence system: weekly rhythm, governance checkpoints, scorecards, reviews.",
    "outputPath": "/assets/downloads/content-downloads/operating-cadence-pack.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.6 KB",
    "lastModified": "2026-01-23T12:06:23.835Z",
    "exists": true,
    "tags": [
      "operations",
      "execution",
      "cadence",
      "governance"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "1935b3a15a35bde5eeb895d24fce4668"
  },
  {
    "id": "principles-for-my-son-cue-card",
    "title": "Principles for My Son - Cue Card",
    "description": "Two-up A6: cut, carry, and read a line a day.",
    "excerpt": "Two-up A6: cut, carry, and read a line a day.",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son-cue-card.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Fatherhood",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 KB",
    "lastModified": "2026-01-23T12:06:23.854Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "ba6c6188962f3c4443911c5ed7d9c091"
  },
  {
    "id": "principles-for-my-son",
    "title": "Principles for My Son",
    "description": "Twelve principles for raising a boy who becomes a man of conviction in a confused age.",
    "excerpt": "Twelve principles for raising a boy who becomes a man of conviction in a confused age.",
    "outputPath": "/assets/downloads/content-downloads/principles-for-my-son.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-23T12:06:23.877Z",
    "exists": true,
    "tags": [
      "fatherhood",
      "legacy"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "caab252ac167a7d1a22a0b5e034c4948"
  },
  {
    "id": "purpose-pyramid-worksheet",
    "title": "Purpose Pyramid Worksheet",
    "description": "A fillable worksheet that turns vision into architecture: purpose → priorities → execution.",
    "excerpt": "Not a motivational prompt. A decision instrument.",
    "outputPath": "/assets/downloads/content-downloads/purpose-pyramid-worksheet.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Vault",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "1.1 KB",
    "lastModified": "2026-01-23T12:06:23.895Z",
    "exists": true,
    "tags": [
      "purpose",
      "strategy",
      "execution",
      "vault"
    ],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "7e4262f35ac5142d7e7d2234600d5b41"
  },
  {
    "id": "scripture-track-john14",
    "title": "Scripture Track - John 14",
    "description": "Assurance • Obedience • The Helper • Peace",
    "excerpt": "Assurance • Obedience • The Helper • Peace",
    "outputPath": "/assets/downloads/content-downloads/scripture-track-john14.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Faith",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "3.0 KB",
    "lastModified": "2026-01-23T12:06:23.915Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "a54d913a9b3416170306ff4c8de00dd0"
  },
  {
    "id": "standards-brief",
    "title": "Standards Brief",
    "description": "Protect people, work, and name-especially under pressure.",
    "excerpt": "Protect people, work, and name-especially under pressure.",
    "outputPath": "/assets/downloads/content-downloads/standards-brief.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Leadership",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.8 KB",
    "lastModified": "2026-01-23T12:06:23.935Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "12ae08101a5ed55e0434f6703947c2b7"
  },
  {
    "id": "ultimate-purpose-of-man-editorial",
    "title": "Ultimate Purpose Of Man Editorial",
    "description": "Ultimate Purpose Of Man Editorial - A resource from Abraham of London",
    "excerpt": "Ultimate Purpose Of Man Editorial - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/ultimate-purpose-of-man-editorial.pdf",
    "type": "editorial",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.3 MB",
    "lastModified": "2026-01-02T17:18:50.915Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "cbbae65b374cf047590e73255d3912f4"
  },
  {
    "id": "weekly-operating-rhythm",
    "title": "Weekly Operating Rhythm & Daily Blocks",
    "description": "A template for high-leverage allocation of time and focus across the week.",
    "excerpt": "A template for high-leverage allocation of time and focus across the week.",
    "outputPath": "/assets/downloads/content-downloads/weekly-operating-rhythm.pdf",
    "type": "Download",
    "format": "PDF",
    "isInteractive": false,
    "isFillable": false,
    "category": "Business",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "2.8 KB",
    "lastModified": "2026-01-23T12:06:23.955Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "f5310f411d66efc41bb6e60e4743b103"
  },
  {
    "id": "decision-matrix-scorecard-fillable",
    "title": "Decision Matrix Scorecard Fillable",
    "description": "Decision Matrix Scorecard Fillable - A resource from Abraham of London",
    "excerpt": "Decision Matrix Scorecard Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/decision-matrix-scorecard-fillable.pdf",
    "type": "tool",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "35.8 KB",
    "lastModified": "2026-01-23T12:06:23.981Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "c1fc54c41c0f1b3e9fb6bad0c05b39a8"
  },
  {
    "id": "legacy-canvas-fillable",
    "title": "Legacy Canvas Fillable",
    "description": "Legacy Canvas Fillable - A resource from Abraham of London",
    "excerpt": "Legacy Canvas Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/legacy-canvas-fillable.pdf",
    "type": "canvas",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "legacy",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "10.5 KB",
    "lastModified": "2026-01-23T12:06:24.005Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b64bd18cce2ac1ba63fb7e4662025b30"
  },
  {
    "id": "purpose-pyramid-worksheet-fillable",
    "title": "Purpose Pyramid Worksheet Fillable",
    "description": "Purpose Pyramid Worksheet Fillable - A resource from Abraham of London",
    "excerpt": "Purpose Pyramid Worksheet Fillable - A resource from Abraham of London...",
    "outputPath": "/assets/downloads/lib-pdf/purpose-pyramid-worksheet-fillable.pdf",
    "type": "worksheet",
    "format": "PDF",
    "isInteractive": true,
    "isFillable": true,
    "category": "downloads",
    "tier": "free",
    "formats": [
      "A4"
    ],
    "fileSize": "19.8 KB",
    "lastModified": "2026-01-23T12:06:24.030Z",
    "exists": true,
    "tags": [],
    "requiresAuth": false,
    "version": "1.0.0",
    "priority": 10,
    "preload": false,
    "md5": "b37f145c3c79e6c6b8ba39385620cfb3"
  }
] as const;
export const GENERATED_AT = "2026-01-23T12:06:24.031Z";
export const GENERATED_COUNT = 29;
