[build]
  command = "npm run build"

[build]  # This is a duplicate and will cause the error
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"