[build]
  base = "abraham-of-london"
  command = "npm ci && npm run build"
  publish = "abraham-of-london/out"

[functions]
  directory = "abraham-of-london/netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_URL = "https://api.codexplatform.com"
  SECRET_KEY = "your-production-secret-key"
  API_URL = "https://api.example.com"