[build]
  command = "npm install && npm run build"
  publish = ".next" # Next.js builds to .next by default relative to base
  # base = "/" # This is the default, so you can omit it or include it for clarity

[functions]
  # Adjust this if your functions are in a different path, e.g., "src/netlify/functions"
  directory = "netlify/functions" 

[[plugins]]
package = "@netlify/plugin-nextjs"