/* lib/intelligence/watermark-delegate.ts — BRAND-EQUITY FORENSIC WATERMARK (AOL-WM-V1) */
import "server-only";

import { createHmac, randomBytes, timingSafeEqual } from "crypto";

/**
 * Classification labels (display layer).
 * Keep this stable; do NOT rename casually—these end up in docs and audit trails.
 */
export type WatermarkClassification =
  | "PUBLIC"
  | "MEMBER"
  | "INNER_CIRCLE"
  | "ARCHITECT"
  | "OWNER"
  | "PRINCIPAL";

export type WatermarkScheme = "AOL-WM-V1";

/**
 * A signature is BOTH:
 * - a human-visible stamp (sig/traceId)
 * - a verification payload (proof) you can store in DB metadata or audit logs
 *
 * Never expose memberId/briefId directly.
 */
export type DossierSignature = {
  scheme: WatermarkScheme;
  sig: string; // human-visible signature: AOL-XXXXXXXXXXXXXXX
  traceId: string; // internal correlation token (non-PII)
  issuedAt: string; // ISO timestamp
  nonce: string; // randomness for uniqueness
  issuer: {
    brand: string;
    issuerId: string; // stable ID of issuing system/environment
  };
  proof: {
    memberHash: string;
    briefHash: string;
    hmac: string; // full HMAC for verification
  };
};

export type WatermarkPayload = {
  // prominent but professional footer line
  visibleFooter: string;

  // repeated faint overlay token (engine decides how to tile/opacity)
  overlayToken: string;

  // recommended overlay styling hints (engine-agnostic)
  overlayHints: {
    rotationDeg: number;
    opacity: number; // 0..1
    fontSize: number;
    letterSpacing: number;
  };

  // document metadata container to embed into the PDF
  metadata: Record<string, unknown>;
};

function mustGetSecret(name: string, minLen: number): string {
  const v = process.env[name];
  if (!v || v.trim().length < minLen) {
    throw new Error(
      `[WATERMARK] Missing/weak ${name}. Set a strong secret (>=${minLen} chars).`
    );
  }
  return v.trim();
}

function getBrand(): string {
  return (process.env.AOL_BRAND_NAME || "Abraham of London").trim();
}

/**
 * Issuer ID lets you distinguish signatures generated by:
 * - local dev
 * - preview
 * - production
 * - a future second app / internal generator
 */
function getIssuerId(): string {
  // Stable across restarts but different across environments.
  // Must not leak secrets: it's used as a label, not as a key.
  return (process.env.AOL_ISSUER_ID || process.env.VERCEL_ENV || process.env.NODE_ENV || "unknown")
    .toString()
    .trim()
    .toUpperCase();
}

/**
 * Master key for HMAC. Rotate via env by changing SYSTEM_INTEGRITY_SALT.
 * (You can later support multiple keys; scheme versioning already exists.)
 */
function getIntegritySalt(): string {
  return mustGetSecret("SYSTEM_INTEGRITY_SALT", 16);
}

/**
 * Secret used to shorten hashes. Keeps memberHash/briefHash stable but non-reversible.
 * Defaults to SYSTEM_INTEGRITY_SALT if you don't set a dedicated one.
 */
function getHashSalt(): string {
  return (process.env.AOL_HASH_SALT && process.env.AOL_HASH_SALT.trim().length >= 16)
    ? process.env.AOL_HASH_SALT.trim()
    : getIntegritySalt();
}

function hmacHex(key: string, payload: string): string {
  return createHmac("sha256", key).update(payload).digest("hex");
}

function shortHash(label: string, value: string): string {
  const salt = getHashSalt();
  return createHmac("sha256", salt)
    .update(`${label}:${value}`)
    .digest("hex")
    .slice(0, 12);
}

function makeNonce(): string {
  // 96 bits is plenty; keeps sig unique without being huge
  return randomBytes(12).toString("hex"); // 24 chars
}

function sigFromHmac(hmac: string): string {
  // Keep it premium and short: 16 hex chars is readable and looks intentional
  return `AOL-${hmac.slice(0, 16).toUpperCase()}`;
}

function traceFrom(memberHash: string, briefHash: string, nonce: string): string {
  // Compact correlation token for logs/support
  return `${memberHash.slice(-4)}-${briefHash.slice(-4)}-${nonce.slice(-4)}`.toUpperCase();
}

/**
 * Generates a forensic-grade signature for a document.
 * - No raw memberId leaked
 * - Verifiable later using SYSTEM_INTEGRITY_SALT
 * - Includes issuer metadata for audit and provenance
 */
export function generateDossierSignature(
  memberId: string,
  briefId: string,
  opts?: { issuedAt?: string; nonce?: string; brand?: string }
): DossierSignature {
  const scheme: WatermarkScheme = "AOL-WM-V1";
  const brand = (opts?.brand || getBrand()).trim();
  const issuerId = getIssuerId();

  const issuedAt = (opts?.issuedAt || new Date().toISOString()).trim();
  const nonce = (opts?.nonce || makeNonce()).trim();

  // Privacy-preserving identifiers (secret-bound)
  const memberHash = shortHash("member", memberId);
  const briefHash = shortHash("brief", briefId);

  // Proof payload ties everything together (versioned)
  const proofPayload = `${scheme}|${issuerId}|${memberHash}|${briefHash}|${issuedAt}|${nonce}`;
  const hmac = hmacHex(getIntegritySalt(), proofPayload);

  const sig = sigFromHmac(hmac);
  const traceId = traceFrom(memberHash, briefHash, nonce);

  return {
    scheme,
    sig,
    traceId,
    issuedAt,
    nonce,
    issuer: { brand, issuerId },
    proof: { memberHash, briefHash, hmac },
  };
}

/**
 * Creates a brand-grade watermark payload for PDF engines.
 * This returns strings + metadata only; rendering is done by React-PDF/Puppeteer etc.
 */
export function getWatermarkPayload(params: {
  signature: DossierSignature;
  classification: WatermarkClassification;
  context?: {
    briefTitle?: string;
    route?: string;
  };
}) : WatermarkPayload {
  const { signature, classification, context } = params;

  const footerLine =
    `${classification} // PROPRIETARY INTELLIGENCE // ` +
    `SIG ${signature.sig} // TRACE ${signature.traceId} // ` +
    `${signature.issuer.brand} // ${signature.issuer.issuerId}`;

  // Token is designed to be tiled faintly across the page
  const overlayToken =
    `AUTHORIZED:${classification}:${signature.sig}:${signature.traceId}:${signature.issuer.issuerId}`;

  const metadata: Record<string, unknown> = {
    author: signature.issuer.brand,
    subject: "Institutional Intelligence Brief",
    keywords: `${signature.sig},${classification},${signature.traceId},${signature.issuer.issuerId}`,
    aol: {
      scheme: signature.scheme,
      classification,
      sig: signature.sig,
      traceId: signature.traceId,
      issuedAt: signature.issuedAt,
      nonce: signature.nonce,
      issuer: signature.issuer,
      context: context || {},
      proof: signature.proof, // store this in the PDF metadata for forensic verification
    },
  };

  return {
    visibleFooter: footerLine,
    overlayToken,
    overlayHints: {
      rotationDeg: -28,
      opacity: 0.06,
      fontSize: 10,
      letterSpacing: 1.6,
    },
    metadata,
  };
}

/**
 * Cryptographic verification (timing-safe compare).
 * Returns true only if the signature matches the proof under current salt.
 */
export function verifyDossierSignature(sig: DossierSignature): boolean {
  try {
    const scheme: WatermarkScheme = "AOL-WM-V1";
    if (sig.scheme !== scheme) return false;

    const payload =
      `${sig.scheme}|${sig.issuer.issuerId}|${sig.proof.memberHash}|${sig.proof.briefHash}|${sig.issuedAt}|${sig.nonce}`;
    const expected = hmacHex(getIntegritySalt(), payload);

    // Timing-safe compare (avoid leaking info in edge cases)
    const a = Buffer.from(sig.proof.hmac, "hex");
    const b = Buffer.from(expected, "hex");
    if (a.length !== b.length) return false;
    if (!timingSafeEqual(a, b)) return false;

    // Ensure sig label matches expected hmac prefix
    return sig.sig === sigFromHmac(expected);
  } catch {
    return false;
  }
}

/**
 * LEGACY COMPATIBILITY (do not remove until all callers migrate).
 * Some existing routes import `getWatermarkStyles(signature: string)`.
 * We provide a professional wrapper that preserves that API but is powered by the new system.
 */
export function getWatermarkStyles(signature: string) {
  const brand = getBrand();
  const issuerId = getIssuerId();

  return {
    visibleFooter: `PROPRIETARY INTELLIGENCE // SIG ${signature} // ${brand} // ${issuerId}`,
    opacityOverlay: `AUTHORIZED:${signature}:${issuerId}`,
    metadata: {
      author: brand,
      subject: "Institutional Intelligence Brief",
      keywords: `${signature},${issuerId}`,
    },
  };
}