/* pages/api/downloads/resolve/[slug].ts — CANONICAL UNLOCK ENDPOINT (SSOT) */
import type { NextApiRequest, NextApiResponse } from "next";
import { allDownloads } from "contentlayer/generated";
import tiers, { requiredTierFromDoc } from "@/lib/access/tiers";
import { getInnerCircleAccess } from "@/lib/inner-circle/access.server";
import { getTokenForensics } from "@/lib/premium/download-token";
import { createDownloadToken } from "@/lib/premium/download-token";

// Define the return type from getInnerCircleAccess
type InnerCircleAccess = {
  hasAccess: boolean;
  reason?: string;
  id?: string;           // This matches your model's primary key
  sessionId?: string;
  tier?: string;
  // ... other fields
};

/**
 * Ensures slug parameters are sanitized and normalized for system lookup.
 */
function normalizeSlugParam(input: unknown): string {
  const s = String(input ?? "")
    .trim()
    .replace(/\\/g, "/")
    .replace(/^\/+/, "")
    .replace(/\/+$/, "")
    .replace(/\/{2,}/g, "/");
  
  if (!s || s.includes("..")) return "";
  // Extracts the final segment to match against the flat slug index
  return s.split("/").filter(Boolean).pop() || "";
}

function extractWatermarkFromDoc(doc: any): { 
  watermarkId?: string | null; 
  tokenId?: string | null;
  forensicFooter?: string | null;
} {
  const metadata = doc.metadata ?? doc.forensics ?? {};
  
  return {
    watermarkId: metadata.watermarkId ?? null,
    tokenId: metadata.tokenId ?? null,
    forensicFooter: metadata.expectedFooter ?? null,
  };
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    res.setHeader("Allow", "GET");
    return res.status(405).json({ ok: false, reason: "METHOD_NOT_ALLOWED" });
  }

  // Security headers to prevent unauthorized caching of sensitive intelligence
  res.setHeader("Cache-Control", "private, no-store, must-revalidate");
  res.setHeader("Vary", "Cookie");

  const slug = normalizeSlugParam(req.query.slug);
  if (!slug) return res.status(400).json({ ok: false, reason: "BAD_SLUG" });

  // Cross-reference against the allDownloads collection generated by Contentlayer
  const doc = (allDownloads as any[]).find((d: any) => 
    String(d?.slugSafe || d?.slug || "").replace(/^\/+/, "") === slug
  );

  if (!doc || doc?.draftSafe) {
    return res.status(404).json({ ok: false, reason: "NOT_FOUND" });
  }

  // Extract forensic data
  const { watermarkId, tokenId: existingTokenId, forensicFooter } = extractWatermarkFromDoc(doc);

  // Determine the institutional clearance level required
  const required = tiers.normalizeRequired(requiredTierFromDoc(doc));
  
  if (required === "public") {
    // For public docs, optionally create a short-lived token
    let token = existingTokenId;
    let wmId = watermarkId;
    
    if (!token) {
      // Create a lightweight token for public access
      const publicToken = await createDownloadToken({
        contentId: slug,
        expiresIn: 5 * 60 * 1000, // 5 minutes
        maxDownloads: 100,
        metadata: { public: true, slug },
      }).catch(() => null);
      
      if (publicToken) {
        token = publicToken.tokenId;
        const forensics = getTokenForensics(publicToken.metadata || {});
        wmId = forensics.watermarkId;
      }
    }

    return res.status(200).json({ 
      ok: true, 
      requiredTier: required, 
      bodyCode: doc.body?.code || doc.bodyCode || "",
      watermarkId: wmId,
      tokenId: token,
      forensicFooter,
    });
  }

  // Execute Inner Circle clearance check (Standardized via Redis/Auth cookies)
  const access = await getInnerCircleAccess(req) as InnerCircleAccess | null;
  
  if (!access?.hasAccess) {
    return res.status(401).json({ 
      ok: false, 
      reason: access?.reason || "REQUIRES_AUTH", 
      requiredTier: required,
      requiredTierLabel: tiers.getLabel(required),
    });
  }

  const userTier = tiers.normalizeUser(access?.tier ?? "public");
  
  if (!tiers.hasAccess(userTier, required)) {
    return res.status(403).json({ 
      ok: false, 
      reason: "INSUFFICIENT_TIER", 
      requiredTier: required,
      requiredTierLabel: tiers.getLabel(required),
      userTier: tiers.getLabel(userTier),
    });
  }

  // Create a download token for authorized access
  let tokenId = existingTokenId;
  let wmId = watermarkId;
  
  if (!tokenId) {
    // ✅ FIXED: Use 'id' which matches your InnerCircleMember model
    const authToken = await createDownloadToken({
      contentId: slug,
      userId: access.id,           // Changed from memberId to id
      sessionId: access.sessionId,
      expiresIn: 24 * 60 * 60 * 1000, // 24 hours
      maxDownloads: 3,
      metadata: {
        tier: userTier,
        slug,
        authorized: true,
      },
    }).catch((error) => {
      console.error("[TOKEN_CREATION_ERROR]", error);
      return null;
    });
    
    if (authToken) {
      tokenId = authToken.tokenId;
      const forensics = getTokenForensics(authToken.metadata || {});
      wmId = forensics.watermarkId;
    }
  }

  // Return the compiled manuscript for UI injection with forensic data
  return res.status(200).json({ 
    ok: true, 
    requiredTier: required, 
    bodyCode: doc.body?.code || doc.bodyCode || "",
    watermarkId: wmId,
    tokenId,
    forensicFooter,
    userTier: tiers.getLabel(userTier),
    downloadUrl: tokenId ? `/api/dl/${tokenId}?resource=${slug}` : null,
  });
}