export type OversightOperatorRole =
  | "SUPER_ADMIN"
  | "OPERATOR"
  | "REVIEWER"
  | "COUNSEL"
  | "FINANCE"
  | "SPONSOR"
  | "RESPONDENT";

export type OversightOperatorPermission =
  | "OVERSIGHT_REVIEW"
  | "OVERSIGHT_DELIVERY"
  | "OVERSIGHT_ARCHIVE"
  | "COUNSEL_WORKFLOW"
  | "COUNSEL_ASSIGNED_ONLY"
  | "BILLING_VIEW"
  | "CLIENT_SAFE_VIEW";

export const OPERATOR_ROLE_PERMISSIONS: Record<OversightOperatorRole, OversightOperatorPermission[]> = {
  SUPER_ADMIN: ["OVERSIGHT_REVIEW", "OVERSIGHT_DELIVERY", "OVERSIGHT_ARCHIVE", "COUNSEL_WORKFLOW", "BILLING_VIEW", "CLIENT_SAFE_VIEW"],
  OPERATOR: ["OVERSIGHT_REVIEW", "OVERSIGHT_DELIVERY", "OVERSIGHT_ARCHIVE", "COUNSEL_WORKFLOW", "CLIENT_SAFE_VIEW"],
  REVIEWER: ["OVERSIGHT_REVIEW", "CLIENT_SAFE_VIEW"],
  COUNSEL: ["COUNSEL_WORKFLOW"],
  FINANCE: ["BILLING_VIEW"],
  SPONSOR: ["CLIENT_SAFE_VIEW"],
  RESPONDENT: [],
};
