// components/downloads/DownloadsGrid.tsx (FULLY ROBUST VERSION)
"use client";

import * as React from "react";
import Link from "next/link";
import clsx from "clsx";

// ----------------------------------------------------------------------
// ✅ ROBUST FIX: Expanded DownloadItem Type
//
// This type is expanded to include properties like 'size' and 'bytes'
// which are generated by the lib/downloads.ts file, ensuring the component
// is robust against variations in the data it receives.
// ----------------------------------------------------------------------
export type DownloadItem = {
  href: string; // public URL (e.g. "/downloads/Mentorship_Starter_Kit.pdf")
  title: string; // pretty title (e.g. "Mentorship Starter Kit")
  sub?: string | null; // Optional subtitle/descriptor for display (e.g., "A4 / US Letter")

  // Properties that may be available but aren't always used for grid display
  file?: string;
  bytes?: number;
  size?: string; // Human readable size (e.g., "45 KB")
  modified?: string;
  ext?: string;
};

type Props = {
  items: DownloadItem[];
  columns?: 1 | 2 | 3;
  className?: string;
};

// ----------------------------------------------------------------------
// Component Logic
// ----------------------------------------------------------------------
export default function DownloadsGrid({
  items,
  columns = 2,
  className = "",
}: Props) {
  // CRITICAL FIX: Ensure items is an array before mapping
  const safeItems = Array.isArray(items) ? items : [];

  const grid =
    columns === 1
      ? "grid-cols-1"
      : columns === 3
        ? "grid-cols-1 sm:grid-cols-2 lg:grid-cols-3"
        : "grid-cols-1 sm:grid-cols-2";

  return (
    <ul className={clsx(`grid gap-6`, grid, className)}>
      {safeItems.map((it) => (
        // CRITICAL FIX: Use slug for key if href contains parameters/variants
        <li key={it.href || it.title}>
          <Link
            // CRITICAL FIX: Ensure href is a string for the Link component
            href={String(it.href)}
            prefetch={false}
            className="group block rounded-2xl border border-lightGrey bg-white p-5 shadow-card transition hover:shadow-cardHover focus:outline-none focus-visible:ring-2"
            aria-label={String(it.title)}
          >
            <div className="flex items-center justify-between gap-4">
              <div>
                {/* ROBUST: Ensure title is always a string */}
                <div className="font-serif text-xl font-semibold text-deepCharcoal">
                  {String(it.title)}
                </div>

                {/* ROBUST: Only render subtitle if it exists and is non-empty */}
                {it.sub?.trim() && (
                  <div className="mt-1 text-sm text-[color:var(--color-on-secondary)/0.8]">
                    {it.sub}
                  </div>
                )}

                {/* Optional: Display Size if available in the DownloadItem data */}
                {it.size && !it.sub && (
                  <div className="mt-1 text-sm text-[color:var(--color-on-secondary)/0.8]">
                    {it.size}
                  </div>
                )}
              </div>
              <span
                aria-hidden
                className="text-softGold transition group-hover:translate-x-0.5"
              >
                ↗
              </span>
            </div>
          </Link>
        </li>
      ))}
    </ul>
  );
}
