// lib/decision/sample-assets.ts
import type { DecisionAsset } from "@/lib/decision/asset-matcher";

export const SAMPLE_DECISION_ASSETS: DecisionAsset[] = [
  {
    id: "brief-operational-clarity-reset",
    title: "Operational Clarity Reset",
    kind: "brief",
    href: "/briefs/operational-clarity-reset",
    summary: "Used when strategic intent is diluted through weak operating translation.",
    orgStates: ["MISALIGNED", "DISORDERED"],
    dominantDomains: ["OPERATIONAL_CLARITY", "STRATEGIC_INTENT"],
    failureModes: ["Strategic-operational misalignment", "Systemic structural disorder"],
    requiredInterventions: ["Re-sequence strategic priorities", "Stabilize operating environment"],
    readinessTiers: ["DIAGNOSTIC", "ADVISORY", "EXECUTION"],
    priorityWeight: 6,
  },
  {
    id: "playbook-burnout-containment",
    title: "Burnout Containment Playbook",
    kind: "playbook",
    href: "/playbook/burnout-containment",
    summary: "Activates when execution fragility is likely to distort all subsequent decisions.",
    failureModes: ["Execution fragility"],
    requiredInterventions: ["Reduce execution strain before transformation load"],
    readinessTiers: ["DIAGNOSTIC", "ADVISORY"],
    priorityWeight: 8,
  },
  {
    id: "doctrine-decision-rights",
    title: "Decision Rights Doctrine",
    kind: "doctrine",
    href: "/canon/decision-rights-doctrine",
    summary: "Used where sponsor ambiguity blocks clean intervention.",
    failureModes: ["Decision-rights ambiguity"],
    requiredInterventions: ["Clarify decision owner and sponsor"],
    readinessTiers: ["DIAGNOSTIC", "ADVISORY", "EXECUTION"],
    priorityWeight: 5,
  },
  {
    id: "framework-volatility-short-horizon",
    title: "Volatility Short-Horizon Framework",
    kind: "framework",
    href: "/strategy/volatility-short-horizon",
    summary: "Used under high external volatility.",
    marketRiskBands: ["HIGH", "CRITICAL"],
    requiredInterventions: ["Adjust decision horizon for external volatility"],
    priorityWeight: 4,
  },
  {
    id: "report-module-strategy-room-escalation",
    title: "Strategy Room Escalation Module",
    kind: "report-module",
    href: "/strategy-room",
    summary: "Used where strategic escalation is justified.",
    appliesTo: ["STRATEGY", "HIGH", "CRITICAL", "SOVEREIGN", "DIRECT", "PROXY"],
    readinessTiers: ["ADVISORY", "EXECUTION", "SOVEREIGN"],
    priorityWeight: 10,
  },
];