"use client";

import React from "react";
import { useOGRStore } from "@/store/useOGRStore";
import { Info, MousePointer2, Calculator, Variable } from "lucide-react";

interface InspectorProps {
  type: "tax" | "velocity" | "alpha" | "certainty";
  children: React.ReactNode;
}

export default function FormulaInspector({ type, children }: InspectorProps) {
  const { resonanceScore, marketFriction, targetRevenue, computed } = useOGRStore();

  const getFormulaData = () => {
    switch (type) {
      case "tax":
        return {
          label: "Integration Tax (Itax)",
          formula: "((100 - R) * 1.25) + (F * 0.05)",
          calc: `((100 - ${resonanceScore}) * 1.25) + (${marketFriction} * 0.05)`,
          result: computed.integrationTax,
          desc: "Cost of aligning dissonance into the OGR Core."
        };
      case "velocity":
        return {
          label: "Velocity Multiplier (Vmult)",
          formula: "R / (100 - F)",
          calc: `${resonanceScore} / (100 - ${marketFriction})`,
          result: computed.velocityMultiplier,
          desc: "Speed of execution relative to market resistance."
        };
      case "alpha":
        return {
          label: "Resonance Alpha (α)",
          formula: "Rev * (Legacy Drag - OGR Drag)",
          calc: `${targetRevenue}M * ((${marketFriction}/100) - ((100-${resonanceScore})/100))`,
          result: computed.resonanceAlpha,
          desc: "Direct capital surplus generated by geometric efficiency."
        };
      case "certainty":
        return {
          label: "Sovereign Certainty (Csov)",
          formula: "(R * 0.7) + ((100 - F) * 0.3)",
          calc: `(${resonanceScore} * 0.7) + ((100 - ${marketFriction}) * 0.3)`,
          result: computed.sovereignCertainty,
          desc: "Deterministic probability of move success."
        };
    }
  };

  const data = getFormulaData();

  return (
    <div className="group relative inline-block">
      {/* The Triggering Value */}
      <div className="cursor-help border-b border-dotted border-[#8A6A2F]/40 hover:text-[#8A6A2F] transition-colors">
        {children}
      </div>

      {/* The Inspector Card (Hover State) */}
      <div className="absolute z-[200] bottom-full left-1/2 -translate-x-1/2 mb-4 w-80 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-all duration-300 transform group-hover:translate-y-0 translate-y-2">
        <div className="bg-[#0F1115] border border-[#8A6A2F]/30 shadow-2xl p-6 backdrop-blur-xl">
          
          <div className="flex items-center gap-3 mb-4 border-b border-white/10 pb-3">
            <Calculator className="w-4 h-4 text-[#8A6A2F]" />
            <span className="font-mono text-[10px] uppercase tracking-widest text-white">
              {data.label}
            </span>
          </div>

          <div className="space-y-4">
            {/* Abstract Formula */}
            <div className="space-y-1">
              <span className="font-mono text-[8px] text-neutral-500 uppercase tracking-tighter flex items-center gap-1">
                <Variable className="w-2 h-2" /> Logic
              </span>
              <code className="block bg-black/40 p-2 text-[10px] text-[#8A6A2F] font-mono leading-tight">
                {data.formula}
              </code>
            </div>

            {/* Live Calculation */}
            <div className="space-y-1">
              <span className="font-mono text-[8px] text-neutral-500 uppercase tracking-tighter">Current Input Trace</span>
              <code className="block bg-black/20 p-2 text-[10px] text-neutral-300 font-mono break-words leading-tight">
                {data.calc}
              </code>
            </div>

            {/* Logic Result */}
            <div className="pt-2 border-t border-white/5 flex justify-between items-end">
              <p className="text-[9px] text-neutral-500 italic max-w-[140px] leading-tight">
                {data.desc}
              </p>
              <div className="text-right">
                <span className="block font-mono text-[8px] text-[#8A6A2F] uppercase">Output</span>
                <span className="text-xl font-serif text-white">{data.result}</span>
              </div>
            </div>
          </div>

          {/* Decorative Pointer */}
          <div className="absolute top-full left-1/2 -translate-x-1/2 w-0 h-0 border-l-[8px] border-l-transparent border-r-[8px] border-r-transparent border-t-[8px] border-t-[#8A6A2F]/30" />
        </div>
      </div>
    </div>
  );
}