[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[context.production.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_URL = "https://api.codexplatform.com"
  SECRET_KEY = "your-production-secret-key"
  API_URL = "https://api.example.com"
